### ISSUE TITLE
Datastore clusters in global configuration?

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry/bosh-vsphere-cpi-release#110]
Would it be possible to add the option of configuring datastore clusters in the global CPI configuration?
Instead of just one regex string for datastores only?
Similar to how the configuration on resource-pool level can be an array of multiple datastores / datastore clusters.

We'd like to be able to specify our datastore cluster's name in the global CPI configuration.

**Comment by nehagjain15** [comment]
@JamesClonk we will take a look at that and update you

**Comment by nehagjain15** [comment]
Pivotal tracker story for same. [#160942636](https://www.pivotaltracker.com/story/show/160942636)

**Comment by julian-hj** [comment]
This feature is fully implemented as of v63
