### ISSUE TITLE
perf: Slow responses for vCenter 6.5 with 25 Director workers

### ISSUE THREAD

**Issue by mxplusb** [cloudfoundry/bosh-vsphere-cpi-release#152]
**Describe the bug**

vCenter can queue up to 2500 operations, and actively perform ~8 operations concurrently. When the BOSH Director is configured with 25 Director Workers and you deploy cf-deployment, the CPI will sit and process the changes for ~10 minutes before registering the tasks with the vCenter queue.

**To Reproduce**
1. Stand up BOSH Director with vSphere 6.5.
1. Set the `compilation.workers` field to 25 in the `cloud-config`.
1. Deploy cf-deployment with at least 3 VMs per instance group.
1. Wait for ~10 minutes for the CPI/vCenter to start queuing tasks.

**CPI Error Log**

No reported errors.

**Expected behavior**

The CPI should start queuing operations for vCenter to execute within a few seconds.

**Screenshots**

N/A

**Release Version & Related Info (please complete the following information):**

```shell
λ  ~  bosh env
Using environment '10.0.4.6' as client 'admin'

Name      bosh
UUID      7d43a2ce-cacb-4ebb-a253-b34428503771
Version   268.0.1 (00000000)
CPI       vsphere_cpi
Features  compiled_package_cache: disabled
          config_server: enabled
          dns: disabled
          snapshots: disabled
User      admin

**Succeeded**
```

VCSA version: 6.5 build 6816762
vCenter Networking: DVS

**Additional context**

This issue is mostly related around performance, there are no errors to report. I first noticed this issue in a home lab running with the VCSA deployed in a "small deployment" configuration with two Dell R710s; my tests were with cf-deployment. I was able to independently reproduce this with the VCSA of the same version in a Dell EMC high performance lab with the VCSA deployed in the "large deployment" configuration; my test was with Pivotal Cloud Foundry 2.1 running in the same configuration. It could potentially be working as intended, but I'm not sure, but since I don't see similar performance concerns with Azure, AWS, or GCP, I figured I'd report it.

**Comment by EleanorRigby** [comment]
What's the CPI version you are using?

**Comment by mxplusb** [comment]
Currently it's deployed with `50`.

**Comment by EleanorRigby** [comment]
We have added this issue to the tracker : https://www.pivotaltracker.com/story/show/160740611 . We will keep you posted when we pick it up. Thanks for clear reporting of issue.

**Comment by mxplusb** [comment]
Awesome! I am really curious as to what would be causing it, please keep me in the loop. :)

**Comment by nehagjain15** [comment]
@mxplusb Can you elaborate more on what you mean by Step #4. Did you mean you started CF deployment at time X and started seeing things in vCenter atafter X+10 minutes? Can you please share your deployment log for CPI so that we can see what was happening in CPI ? You get get the CPI log using bosh task command
```bosh task task# --cpi --debug```

**Comment by mxplusb** [comment]
> Did you mean you started CF deployment at time X and started seeing things in vCenter after X+10 minutes?

This is correct - the time does vary a bit, but 10 minutes seemed to be somewhat average. BOSH + CPI is doing something, but what exactly, I'm not sure. I don't see this behaviour in any of the other CPIs, so I'm guessing it's something specific to the vSphere CPI + something vCenter is doing.

Here is what you see in the BOSH CLI:

```
...
Task 27150 | 15:30:37 | Preparing deployment: Preparing deployment (00:01:22)
Task 27150 | 15:36:47 | Preparing package compilation: Finding packages to compile (00:00:01)
...
```

You'll notice there was a ~6 minute state where seemingly nothing happened and BOSH isn't tracking it. They are large files, so I've attached them to the issue so they don't eat up screen space. `27150.cpi.txt` is the CPI debug output and `27150.bosh.txt` is the task debug output. 

[27150.bosh.txt](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/files/2435404/27150.bosh.txt)
[27150.cpi.txt](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/files/2435405/27150.cpi.txt)

**Comment by nehagjain15** [comment]
@mxplusb First call to CPI was made at
``` 2018-09-19T15:37:28.062265 #16762]  INFO -- [req_id cpi-282367]: Starting info...```
between Preparing deploy and this call it is director which is doing the work and CPI is not involved at that point of time. Creation of Compilation VM is when CPI calls were issued. I think you need to contact BOSH team for this. @dpb587-pivotal can you  help ?

**Comment by dpb587-pivotal** [comment]
We did recently fix some performance issues that were occurring around the "preparing deployment" stage - I'd recommend upgrading to [v267.7.0+](https://github.com/cloudfoundry/bosh/releases/tag/v267.7.0) and see if it helps. The slowness was most pronounced in environments where there were particularly large deployments with numerous VMs.

There are still some performance issues we are investigating around links usages, but v267.7.0 should help a bit if you're not already using it. Care to give that a try and report back if it helps?

**Comment by nehagjain15** [comment]
@mxplusb you can try the above recommendation. I am going to close this issue as it is not CPI bug. If you still see performance issue feel free to open an issue on BOSH.

**Comment by mxplusb** [comment]
@dpb587-pivotal I will give that a try and get back to you in the next week or so.
