### ISSUE TITLE
CPI to create DRS rule to disable VM from DRS.

### ISSUE THREAD

**Issue by agregory999** [cloudfoundry/bosh-vsphere-cpi-release#164]
### Detailed Description
BOSH CPI for vSphere has the ability to create DRS rules, but only for separation.  We'd like to be able to create a rule which tells DRS to disable itself for a specific type of VM.

### Context
Currently the customer would like to use Fully Automated DRS as per our recommendation, but cannot tolerate the potential for clock skew if v-motion occurs for the Diego cells.  Therefore, it would be good to disable DRS for these VMs altogether. 

### Possible Implementation
Cluster-level manipulation, instead of VM-level

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [X ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by agregory999** [comment]
If we can do this today with BOSH, I am willing to propose it as a potential solution to try.

**Comment by yeshwantbabar** [comment]
@agregory999  - We can not do this today in BOSH. We will take this as a feature request. For now, I would suggest going with the approach I mentioned on slack.

**Comment by dbarkelew** [comment]
@yeshwantbabar What about for environments that scale dynamically. Having someone trying to pin the VMs manually is not reliable enough. Do you have any other suggestions for a workaround to set the VM Override so the DRS Automation Level can be controlled by Bosh?

Is there a way to have a Bosh create trigger a script that would in turn set the VM Override for DRS Automation Level? If Bosh can pass the VM name to like the following script example https://github.com/vmware/rbvmomi/blob/master/examples/vm_drs_behavior.rb after the create this might work as a workaround. Could probably have the script run from the same box as Bosh.

Other idea is have a script that is injected to the VM that will set the DRS Automation Level for all VMs with a specific Custom Attribute Key:Value. Problem would be having the password in the script is concerning.

**Comment by yeshwantbabar** [comment]
This is what I had mentioned in slack - 
 1) Right now, customer could select all the Diego cell VMs and disable DRS on them. Documented here :http://www.yellow-bricks.com/2018/03/28/disable-drs-for-a-vm/ This has the obvious drawback which is, if the VMs get recreated you will need to keep updating this.

Is this not an acceptable solution?

**Comment by agregory999** [comment]
This is a workaround we can accomplish via script, correct.  However the enhancement request to have BOSH be able to affect this change automatically via the CPI is what we are after.  We'd like to be able to have this set directly upon VM creation.

**Comment by yeshwantbabar** [comment]
@agregory999 @dbarkelew  - What I am suggesting above is just as a workaround in the meantime while we add this functionality. My understanding was that customer wants to solve this problem ASAP.  As I have mentioned on slack, we are open adding this new functionality. but It will take some time for us to implement this and have OM pick it up.  Rest assured, this will be available in the next CPI release.

**Comment by dbarkelew** [comment]
Right now trying to figure out some ad hoc script to achieve the same because there is a huge push to have this everything ready in December since the go live is beginning of January. Any thoughts if the next release has a possibility of being released before the deployment official go live? (Is already live on a limited bases.)

Got something to handle when cells are created however there are a few issues with Bosh redeploying VMs as a corrective a measure. Finding an event to reliably trigger the script to set the VM override back is proving to be a problem. Any suggestions are welcome. Right now trying to find a way to use a script from inside the VM to get the VM name and use this to ensure the VM override is correct each time and the trigger would be to run each as part of the VM boot process.
