### ISSUE TITLE
Deleted VMs leave components behind

### ISSUE THREAD

**Issue by BrianRagazzi** [cloudfoundry/bosh-vsphere-cpi-release#165]
**Describe the bug**
When a VM is deleted by the CPI, a namespace/folder and some subfolders are left behind.  VSAN has a limit on the number of components per host; when these objects are not purged, they continue to count toward the limit.  When the limit (9000) is reached, VSAN stops provisioning new objects.

**To Reproduce**
Given an environment of vSphere 6.5 U2, NSX-T 2.2, Pivotal Operations Manager 2.2.x or (BOSH v267.3.0 and BOSH vSphere CPI release v50) 
1. Make a note of the number of VSAN components per host.  This can be gathered via the vSphere web client (Cluster|Monitor|VSAN Tab|Health|Limits->Host component limit) or the "vsan.check_limits" action in rvc.
2. Deploy a release to an AZ that corresponds to a VSAN-backed vSphere cluster
3.  Make a note of the number of VSAN components per host; note that it has increased by approximately 3 times the number of VMs deployed
4. Destroy the deployment
5. Make a note of the number of VSAN components per host; note that it has not decreased to the value recorded in step 1

**Expected behavior**
The number of VSAN components to return to its original pre-deployment value when a deployment is deleted

**Release Version & Related Info**
 - CPI Version v50
 - BOSH Director Version v267.3.0 or PAS v2.2.x
 - Stemcell Name & Version Trusty 3468.55
 - vCenter Version v6.5u2
 - NSX(T/V) Version (If using) NSX-T 2.2

**Comment by nehagjain15** [comment]
@BrianRagazzi This is a vCenter bug which has been fixed in v6.5p03 and v6.7u1.
Also, to clean up your deployment completely you also need to run ```bosh clean-up``` to clean up releases, stemcells and orphaned disks as well

**Comment by xyloman** [comment]
@nehagjain15 we experiencing a similar issue and we have v6.5.0 U2c: https://my.vmware.com/web/vmware/details?productId=614&rPId=27739&downloadGroup=VC65U2C is there a version newer than this that we would need to request from VMWare that contain the fix?

**Comment by nehagjain15** [comment]
@xyloman I think it will be part of v6.5.0 U2d which is not GA yet. You can use 6.7u1 which has the fix as well.

**Comment by nehagjain15** [comment]
@BrianRagazzi @xyloman  6.5 U2d is GA now which has the fix for this

**Comment by nehagjain15** [comment]
@BrianRagazzi Closing this. If you see this issue again feel free to open a new one.

**Comment by BrianRagazzi** [comment]
Thank you.  The issue is resolved when using vSphere 6.7 U1
