### ISSUE TITLE
Documentation for workload placement when using multiple clusters on 1 AZ

### ISSUE THREAD

**Issue by DaxterM** [cloudfoundry/bosh-vsphere-cpi-release#188]
As a vsphere CPI bosh user I'd like to understand how the VM placement algorithm works when a single AZ has multiple vsphere clusters. Currently you would have to read the code to understand it.

**Comment by gberche-orange** [comment]
@DaxterM https://bosh.io/docs/vsphere-cpi/#clusters mentions the following

> When placing a VM, a cluster is chosen (along with a datastore) based on the VM's memory, ephemeral disk, and persistent disk requirements.

>VMs are placed on clusters and datastores based on a weighted random algorithm. The weights are calculated by how many times the requested memory, ephemeral and persistent disk could fit on the cluster.

> During VM placement local datastores and shared datastores are not treated differently. All datastores registered on a cluster are treated the same.
Locality¶

> When recreating an existing VM, the CPI tries to create it in a cluster and datastore that are near the largest of its existing persistent disks.

From your reading of the code, what part of the placement algorithm would need refinement in the documentation ?

**Comment by EleanorRigby** [comment]
@DaxterM  : Closing this issue as documentation already exists.
