### ISSUE TITLE
CFCR & RDM or local datastore pinning

### ISSUE THREAD

**Issue by king-jam** [cloudfoundry/bosh-vsphere-cpi-release#193]
## Support Question
I'm trying to deploy CFCR to a vSphere environment. I'd like to be able to use the Kubernetes v1.13.x GA Container Storage Interface support but vSphere support is lacking so I wanted to use something like Ceph, leveraging something like Rook.io. This creates the following requirements:

1) VMs must be pinned to a specific ESXi Host (I believe this is possible via DRS rules with the CPI).
2) VMs must (should really) use local storage from the ESXi host (since Ceph clusters the storage natively). (THIS IS WHAT I DON'T KNOW HOW TO DO).

*The Question*
Is there a way to describe and map specific datastores and/or disks to specific VMs without breaking out every worker in this manifest? https://github.com/cloudfoundry-incubator/kubo-deployment/blob/master/manifests/cfcr.yml#L317-L404

I'd prefer to stay close to the default but understand if I need to create different disk_types for every local disk and have every worker be it's own place in the manifest.

**Comment by EleanorRigby** [comment]
1. VMs must be pinned to a specific ESXi Host (I believe this is possible via DRS rules with the CPI).

This is a feature already delivered. It is pushed to the master #177  .  Yet to cut a release.

2. VMs must (should really) use local storage from the ESXi host

One way is to create VSAN datastore from all local ESXi storage and use that. The `vm_type` field in BOSH manifest can be used to specify datastores you want to put CEPH VMs on. You can create `disk pools` to specify where persistent disks will go.
On the question of how to modify CFCR manifest without breaking other workers, I would suggest opening a support question/issue on their GitHub repository. Developers here are not very familiar with CFCR deployment manifest.

**Comment by EleanorRigby** [comment]
Feel free to re-open the issue if you have more questions.
