### ISSUE TITLE
Support for VM Storage Policies

### ISSUE THREAD

**Issue by mxplusb** [cloudfoundry/bosh-vsphere-cpi-release#200]
### Detailed Description

For vSAN clusters with <3 fault domains, in order to deploy a virtual machine, you have to set a VM Storage Policy that allows for <3 fault domains, i.e., no data redundancy. Without support for custom VM Storage Policies, BOSH cannot deploy a virtual machine backed by a vSAN with <3 fault domains.

### Context

The vSphere Storage Provider for k8s supports vSAN backed deployments, as well as custom VM storage policies, so a hard disk can be attached to a VM using a custom Storage Policy. However, as the CPI doesn't currently support custom Storage Policies, CFCR can't deploy a VM to a vSAN datastore with a custom Storage Policy to use the vSphere Storage Provider with a custom Storage Policy.

Where this could bring benefit is to very small vSAN deployments, allowing for localized BOSH deployments on vSAN clusters with <3 fault domains.

### Possible Implementation

A global flag in the CPI config could be a great starting place.

**Comment by EleanorRigby** [comment]
Hello @mxplusb 

We are in the process of introducing SPBM. https://github.com/cloudfoundry/bosh-vsphere-cpi-release/pull/178

**Comment by mxplusb** [comment]
Oh, well that's nifty! Thanks!

**Comment by EleanorRigby** [comment]
Closing this s SPBM is merged to master and is due to be released. Feel free to open again if there are bugs or expected features are missing.

**Comment by mxplusb** [comment]
I saw, thanks!
