### ISSUE TITLE
CPI vSphere extension does not support self signed certificates from vCenter

### ISSUE THREAD

**Issue by daniellavoie** [cloudfoundry/bosh-vsphere-cpi-release#203]
**Describe the bug**
The vsphere CPI installs the `sddc.cpi.extension` during stemcell creation. I've been told that this  extension is used to warn vpshere operators that Bosh manages the clusters.

vSphere operators still need to rotate certificates with self sign on the center hosts using this [procedure](https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.psc.doc/GUID-41B3B37E-5C48-4333-BA3F-5A00B3BBCC76.html) from VMware. 

The procedure seems to interrogate each extensions. It will fail on the `sddc.cpi.extension` as the extension does not configure any trusted certificate.

**To Reproduce**
1. Install vCenter with a self signed certificate.
2. Create a stemcell with a Bosh director.
3. Apply the [procedure](https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.psc.doc/GUID-41B3B37E-5C48-4333-BA3F-5A00B3BBCC76.html) from VMware.

**VCenter error**
```
Get service 07827601-8429-4200-a5ce-b9f20c89bd36_sddc.cpi.extension
Status : 0% Completed [Operation failed, performing automatic rollback]
```

**Expected behavior**
According to [cpi_extension](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/4ccfaf281ea1449de51ac25f5ac27be4d413657b/src/vsphere_cpi/lib/cloud/vsphere/cpi_extension.rb#L29), it seems that the CPI Extension is not configured with a trust SSL.

Extension definition for the CPI Extension:
```
$ ./lstool.py get --no-check-cert --url https://localhost/lookupservice/sdk --id 07827601-8429-4200-a5ce-b9f20c89bd36_sddc.cpi.extension --as-spec
[…]
serviceType.product=com.vmware.cis
serviceType.type=sddc.cpi.extension
nodeId=f14288ca-d22f-11e8-bf4a-0050568e6441
serviceNameResourceKey=sddc.cpi.extension.label
serviceDescriptionResourceKey=sddc.cpi.extension.summary
```

Extension definition for other extension:
```
$ ./lstool.py get --no-check-cert --url https://localhost/lookupservice/sdk --id d97ce17e-5ec4-49dd-9857-664c3a44e673 --as-spec
[…]
endpoint0.type.protocol=vmomi
endpoint0.type.id=com.vmware.cis.sca
endpoint0.url=https://pzgesnf523.desjardins.com:443/sca
endpoint0.ssltrust0=<redacted-certificate>
endpoint0.data0.key=cis.common.ep.localurl
endpoint0.data0.value=http://localhost:18091/sca
```

**Release Version & Related Info (please complete the following information):**
 - CPI Version : `master`
 - BOSH Director Version : `irrelevant`
 - Stemcell Name & Version `irrelevant`
 - vCenter Version `6.5`
 - NSX-T : `irrelevant`

**Questions**
* What is this extension used for?
* Can it be deleted to perform certification rotation
* Is it possible to support self signed vcenter certificates?

**Comment by EleanorRigby** [comment]
@daniellavoie : I have not seen such an issue before. Maybe nobody attempted cert rotation until now.

1. This extension is used to register VMs created by BOSH and only serves a cosmetic purpose of throwing warnings when anyone tries to perform manual power offs and other operation on these VMs.
2. It cannot be deleted once it is put in.
3. I am not sure how to support self signed cert for extensions. There is no option in the API to do so. https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.Extension.html

When you list extension definition for other types of service above, why does it show different attributes? or have you folded them?

**Comment by daniellavoie** [comment]
Attributes were folded indeed. What is sure is that we have a missing `endpoint0.ssltrust0` on the CPI extension attribute that we get on vmware's other extensions. Is there any workaround you could suggest?

**Comment by EleanorRigby** [comment]
Okay, good to know.

There is currently no straight way to resolve this. One solution I can think off is 
 1. Remove the extension through API call to VC 
 2. then revoke permission on CPI user to create an extension, the `Register_Extension` method in CPI will fail silently without registering the extension.

On the solution part for this problem:
I do not see any field while registering an extension which lets me set an endpoint like above. There is a field here: https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.Extension.html called `ExtensionServerInfo` which does provide a server URL and thumbprint if I want to expose any server. But it is completely optional to do so. 
What is the source of the script `lstools.py`?
How does one start the `procedure` you mentioned above? I saw that on the page of `procedure` there are options to rotate certs in more ways like below 
```
/usr/lib/vmware-vmca/bin/certificate-manager
		 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
		|                                                                     |
		|      *** Welcome to the vSphere 6.5 Certificate Manager  ***        |
		|                                                                     |
		|                   -- Select Operation --                            |
		|                                                                     |
		|      1. Replace Machine SSL certificate with Custom Certificate     |
		|                                                                     |
		|      2. Replace VMCA Root certificate with Custom Signing           |
		|         Certificate and replace all Certificates                    |
		|                                                                     |
		|      3. Replace Machine SSL certificate with VMCA Certificate       |
		|                                                                     |
		|      4. Regenerate a new VMCA Root Certificate and                  |
		|         replace all certificates                                    |
		|                                                                     |
		|      5. Replace Solution user certificates with                     |
		|         Custom Certificate                                          |
		|                                                                     |
		|      6. Replace Solution user certificates with VMCA certificates   |
		|                                                                     |
		|      7. Revert last performed operation by re-publishing old        |
		|         certificates                                                |
		|                                                                     |
		|      8. Reset all Certificates                                      |
		|_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _|
```

Which option to select to reproduce this issue? 
Is it possible to not replace cert on particular extension?

How long is it possible to ignore this issue? I am asking because the bandwidth on team is low for any new feature or bug unless it is a absolute blocker and causing severe failures.

**Comment by EleanorRigby** [comment]
@daniellavoie : Does this KB look like something that could be the issue here : https://kb.vmware.com/s/article/2121701

**Comment by EleanorRigby** [comment]
As per some research I did just now, there is no way of configuring endpoints for the type of `extension` *cpi* registered.
Below are two extensions I configured using `ExtensionServerInfo` option I talked about in above comment. They don't have endpoint still. I suspect this to be a bug in VMware's cert rotate tool. Can you verify this with vSphere support team at customer site?
```
-------------------------------------------------------
	Name: a.sddc.cpi.extension.label
	Description: a.sddc.cpi.extension.summary
	Service Product: com.vmware.cis
	Service Type: a.sddc.cpi.extension
	Service ID: cd80f41a-f350-46a9-89d7-efeac7dda271_a.sddc.cpi.extension
	Site ID: default-first-site
	Node ID: da003d97-bed7-4b62-bfc2-422fcd2235c1
	Owner ID: vpxd-33e4ff7b-5f68-476b-b11a-fde71efa83d4@vsphere.local
	Version: 1.0.0
-------------------------------------------------------
	Name: sddc.cpi.extension.label
	Description: sddc.cpi.extension.summary
	Service Product: com.vmware.cis
	Service Type: sddc.cpi.extension
	Service ID: cd80f41a-f350-46a9-89d7-efeac7dda271_sddc.cpi.extension
	Site ID: default-first-site
	Node ID: da003d97-bed7-4b62-bfc2-422fcd2235c1
	Owner ID: vpxd-33e4ff7b-5f68-476b-b11a-fde71efa83d4@vsphere.local
	Version: 1.0.0
```

**Comment by daniellavoie** [comment]
Wow! That is a very thorough analysis! Thanks @EleanorRigby. It does feel like the cert rotation tool should accept self signed certificate. I think the operator was trying to rotate directly from VCenter. Maybe `certificate-manager` handles the self signed use case. I'll do a bit more of research on that end and probable re-engage VMware support.

I'm closing this issue for now.

**Comment by dstoffel-de** [comment]
Hi,

I'm hitting the same issue.
Just want to add some information.

Which option to select to reproduce this issue?
Option 1 - Replace certificate machine -> import new certificate in the next screen.

Is it possible to not replace cert on particular extension?
=> i don't know but cpi is not the only one to have this kind of behaviour and vmware ask to unregister the extension before applying new certificate. (https://kb.vmware.com/s/article/2150057)

removing the extension when the current certificate is expired is really not easy (and still looking how to do it as you cannot auth anymore on the API)

Raising a case @VMware could be great to have the documentation about the endpoint/ssltrust to provide a new version of CPI extension that will not break standard certificate changes.

Davy

**Comment by dstoffel-de** [comment]
mini howto when you have an expired certificate and connect connect to /mob anymore: 

- cp  /etc/vmware-vpx/ssl/rui.crt /etc/vmware-vpx/ssl/rui.crt.bk
- cp  /etc/vmware-vpx/ssl/rui.key /etc/vmware-vpx/ssl/rui.key.bk
- cp  /etc/vmware-rhttpproxy/ssl/rui.crt /etc/vmware-rhttpproxy/ssl/rui.crt.bk
- cp  /etc/vmware-rhttpproxy/ssl/rui.key /etc/vmware-rhttpproxy/ssl/rui.key.bk
- cp mynewkey /etc/vmware-vpx/ssl/rui.key
- cp mynewcert /etc/vmware-vpx/ssl/rui.crt
- cp mynewkey /etc/vmware-rhttpproxy/ssl/rui.key
- cp mynewcert /etc/vmware-rhttpproxy/ssl/rui.crt

service-control always restore the old certificate during the restart process, so i protect the file from being changed temporarily

- chattr +i  /etc/vmware-vpx/ssl/rui.key
- chattr +i  /etc/vmware-vpx/ssl/rui.crt
- chattr +i  /etc/vmware-rhttpproxy/ssl/rui.key
- chattr +i /etc/vmware-rhttpproxy/ssl/rui.crt

reboot or service-control --stop --all, service-control --start --all

now vpx et rhttp should start with the new certificate and the reverse proxy is able to connect to vpx.

goto https://vcsa/mob/ , content -> extensionManager -> method -> UnregisterExtension -> sddc.cpi.extension

remove the protection
- chattr -i  /etc/vmware-vpx/ssl/rui.key
- chattr -i  /etc/vmware-vpx/ssl/rui.crt
- chattr -i  /etc/vmware-rhttpproxy/ssl/rui.key
- chattr -i /etc/vmware-rhttpproxy/ssl/rui.crt

Re-run certificate-manager, should be successfully this time.

Davy
