### ISSUE TITLE
'Failed to add VM to Security Group with unknown NSX error

### ISSUE THREAD

**Issue by kumarganesh2814** [cloudfoundry/bosh-vsphere-cpi-release#206]
## Support Question

---
Hi Team,

We are seeing below error into our cloud foundry environment lately.

``director
director - error during update deployment
Severity: 3
Summary: Error during update deployment for 'bosh-health-check' against Director 'b8aa6825-3293-4619-b000-083f05bc93d1': #<Bosh::Clouds::ExternalCpi::UnknownError: Unknown CPI error 'Unknown' with message 'Failed to add VM to Security Group with unknown NSX error: '<?xml version="1.0" encoding="UTF-8"?> <error><errorCode>311</errorCode><details>Object vm-10136 is already a member of Security Group securitygroup-3280.</details><moduleName>core-services</moduleName></error>'' in 'create_vm' CPI method>
Time: 2019-04-20 17:05:59 UTC``

Can someone please guide me resolve this from other closed issue seems to be resolved in v32. Doest that mean I need to update bosh director or something?

Best Regards
Ganesh Kumar

**Comment by kumarganesh2814** [comment]
Env Info:

```Name      p-bosh
UUID      b8aa6825-3293-4619-b000-083f05bc93d1
Version   266.13.0 (00000000)
CPI       vsphere_cpi
Features  compiled_package_cache: disabled
          config_server: enabled
          dns: disabled
          snapshots: disabled
User      ops_manager

**Comment by nehagjain15** [comment]
@kumarganesh2814 Are you using NSX-V or NSX-T?  Which version of CPI are you using and which version of NSX-V/NSX-T ?

Can you check in your cloud config that you dont have duplicate security-groups defined for the same

**Comment by EleanorRigby** [comment]
Did you recently upgrade NSXV manager? The similar was fixed in last CPI
patch release.

Tushar

**Comment by kumarganesh2814** [comment]
@nehagjain15 @EleanorRigby 
You are absolutely right we did NSX Manager Upgrade recently.  We are using NSX-V. 

Best Regards
Ganesh Kumar

**Comment by nehagjain15** [comment]
@kumarganesh2814 please use 1 of the CPI releases where support for `NSX-V Manager 6.4.2` was added. I will close the bug and you can reopen it if you see the issue after upgrading CPI

**Comment by kumarganesh2814** [comment]
@nehagjain15 Can you please advise to update bosh vsphere cpi without downtime please.

**Comment by EleanorRigby** [comment]
@kumarganesh2814 : From the env details you shared above, it seems that you are using opsManager to work with BOSH director.
You will need to reach out someone in Pivotal support regarding the upgrade of the ops Manager version which packs the correct CPI release.

**Comment by EleanorRigby** [comment]
CPI release `52.1.0` , `51.1.0` and `50.0.4` supports NSX-V 6.4.x manager. Please refer here for ops-manager release notes: https://docs.pivotal.io/pivotalcf/2-4/pcf-release-notes/opsmanager-rn.html

**Comment by kumarganesh2814** [comment]
Thanks @EleanorRigby Tushar and @nehagjain15  Neha. We will do PCF Ops Manager Upgrade and then NSX.

**Comment by kumarganesh2814** [comment]
@EleanorRigby Tushar and @nehagjain15 Neha
We see this issue on existing infra too now. 
Created Pivotal Case too for same
https://community.pivotal.io/s/case/5000e00001Zz4ekAAB/urgent-prod-failure-for-pcf-unknown-cpi-error-unknown-with-message-failed-to-add-vm-to-security-group-with-unknown-nsx-error

NSX Version:
6.3.3 Build 7087283
Uptime:
422 days, 14 hours, 35 minutes
vSphere:
vCenter: 6.5.0 5973321
Esxi: 6.5.0, 7388607
PCF Ops Manager v2.2-build.359
PAS 2.2.8
