### ISSUE TITLE
Error: Unknown CPI error 'Unknown' with message 'getaddrinfo: Name or service not known (esxi_host:443)' in 'create_stemcell' CPI method

### ISSUE THREAD

**Issue by blackramit** [cloudfoundry/bosh-vsphere-cpi-release#207]
**Describe the bug**

**To Reproduce**
1. Create two instances in one AZ and disk .....
2. Sections of cloud config relevant to bug reproducibility

**CPI Error Log**
Can be obtained by running `bosh <env params> task <failed-task-id> --cpi`

**Expected behavior**

**Screenshots**

**Release Version & Related Info (please complete the following information):**
 - CPI Version 
 - BOSH Director Version
 - Stemcell Name & Version
 - vCenter Version
 - NSX(T/V) Version (If using)

**Additional context**

**Comment by ktchen14** [comment]
No logs or detail in this bug at all. Failure is in `getaddrinfo()` which indicates DNS lookup failure. Host name is `esxi_host` which is probably incorrect.
