### ISSUE TITLE
Error: Unknown CPI error 'Unknown' with message 'getaddrinfo: Name or service not known (esxi_host.something.com:443)' in 'create_stemcell' CPI method

### ISSUE THREAD

**Issue by blackramit** [cloudfoundry/bosh-vsphere-cpi-release#208]
I'm having a real problem getting my initial Stemcell deployed on vCenter/vSphere 6.5u2. I have the Director setup and all seems fine. However, when I try to load my initial Stemcell, I get this error:

```
_Error: Unknown CPI error 'Unknown' with message 'getaddrinfo: Name or service not known (esxi_host.something.com:443)' in 'create_stemcell' CPI method (CPI request ID: 'cpi-366010')_
```

What is frustrating is I have followed ALL of the suggestions regarding DNS setup. My "dig" on the Bosh CLI Platform resolves fine, so DNS is working within my platform. My Cloud_Config displays the Local DNS;

```
[DevAdmin@ealab-devopsmgt bosh-vsphere]$ bosh cloud-config
Using environment '192.168.10.100' as client 'admin'

azs:
cloud_properties:
datacenters:
clusters:
CoopCluster: {}
name: z1
cloud_properties:
datacenters:
clusters:
CoopCluster: {}
name: z2
cloud_properties:
datacenters:
clusters:
CoopCluster: {}
name: z3
compilation:
az: z1
network: default
reuse_compilation_vms: true
vm_type: default
workers: 5
disk_types:
disk_size: 3000
name: default
disk_size: 50000
name: large
networks:
name: default
subnets:
azs:
z1
z2
z3
cloud_properties:
name: VM Network
dns:
192.168.10.20
gateway: 192.168.10.1
range: 192.168.10.0/24
reserved:
192.168.10.1-192.168.10.99
192.168.10.121-192.168.10.255
type: manual
vm_types:
cloud_properties:
cpu: 2
disk: 30000
ram: 1024
name: default
cloud_properties:
cpu: 2
disk: 30240
ram: 4096
name: large
```

My manifest was created as;

```
[DevAdmin@ealab-devopsmgt bosh-vsphere]$ bosh create-env bosh-deployment/bosh.yml -o bosh-deployment/local-dns.yml --state=./state.json --vars-store=./creds.yml -o bosh-deployment/vsphere/cpi.yml -o bosh-deployment/local-dns.yml -v director_name=bosh-director -v internal_cidr=192.168.10.0/24 -v internal_gw=192.168.10.1 -v internal_ip=192.168.10.100 -v network_name="VM Network" -v vcenter_dc=CoopLab -v vcenter_ds=dev_ea -v vcenter_ip=192.168.10.15 -v vcenter_user=administrator@vsphere.local -v vcenter_password=xxxxx -v vcenter_templates=Bosh_Dir/templates -v vcenter_vms=Bosh_Dir/vms -v vcenter_disks=Bosh_Dir/disks -v vcenter_cluster=CoopCluster -v internal_dns=[192.168.10.20]
```

So what am I doing wrong? How do I access logging that might dig into this deeper?  I'm a newbie to Bosh, just trying to learn!

**Comment by ktchen14** [comment]
This error:

```
_Error: Unknown CPI error 'Unknown' with message 'getaddrinfo: Name or service not known ("esxi_host":443)' in 'create_stemcell' CPI method (CPI request ID: 'cpi-366010')_
```

Indicates a problem in hostname resolution. If it's in `create_stemcell` then my guess is that when the BOSH director (or more specifically the CPI) attempts to upload the stemcell OVA to one of the datastores through an ESXi host, it's failing to resolve the DNS name of that host.

It says from that error message that the DNS name of your ESXi host is `esxi_host`. Is that correct? The ESXi host must be reachable and resolvable from the BOSH director itself.

What's the BOSH CLI platform? And can we see the output of the `dig` command?

**Comment by EleanorRigby** [comment]
Similar issue : https://github.com/cloudfoundry/bosh-vsphere-cpi-release/issues/30

**Comment by blackramit** [comment]
The Host name in the error message is accurate, let's call it "esxi-host.something.com".  I can "dig" it on the Bosh CLI Platform fine.  So you are saying that the Director VM on my vCenter Cluster is what is having the issue?

**Comment by blackramit** [comment]
I looked at that #30 issue and it didn't get me anywhere.

**Comment by ktchen14** [comment]
@blackramit Sorry is the ESXi hostname `esxi-host` or `esxi_host`? Also can you provide more details about the BOSH CLI platform? I'm not quite sure what that is.

**Comment by blackramit** [comment]
Hi Ktchen... I have a linux Jumpbox call that the Bosh CLI is deployed on.  That box can resolve the name of my vCenter Appliance and each of my ESXi Hosts just fine.  I have deployed the Director/CPI VM on this platform fine.  So I am set to go.

I tried to deploy my first deployment Stemcell (OVF) from the https://bosh.io/stemcells/ site, but it has failed.  I tried direct from the site using the URL and tried a download.  Tried CentOS and Ubuntu.

The thing is, it does engage vCenter and begin the upload, but it fails in director with this message.  On vCenter the new Template is there for a while, but it times out and disappears.  Here's a screen shot: \

![image](https://user-images.githubusercontent.com/41175867/56759205-adf66d00-6755-11e9-9c67-8581df23c336.png)

![image](https://user-images.githubusercontent.com/41175867/56759235-bf3f7980-6755-11e9-857a-f90740c7bfa2.png)

**Comment by ktchen14** [comment]
@blackramit Okay then the problem is almost definitely in the DNS resolution process from the BOSH director VM itself.

There are two steps to uploading an OVA:

1. The vSphere CPI on the BOSH director contacts vCenter and requests a ticket to upload the OVA
2. The vSphere CPI on the BOSH director extracts the hostname of the ESXi host from the ticket and issues a POST request directly to that host

In this case it looks like step 1 is fine (your BOSH director is able to talk to vCenter). However step 2 is failing (your BOSH director can't talk to the ESXi host). And in particular it looks like the BOSH director VM can't resolve the hostname of the ESXi host to its IP address.

You need to verify that your ESXi's is reachable and its hostname is resolvable from *the network that your BOSH director is deployed on* with *the DNS server that it's configured to use*. It's probably working from your Linux jumpbox because that VM is either on a different network, configured with a different DNS server, or both.

**Comment by blackramit** [comment]
Got it, let me dig into that and I will reply back.  Thanks Ktchen!

**Comment by blackramit** [comment]
Well dang, that isn't it... both my host are setup with the proper DNS settings.

![image](https://user-images.githubusercontent.com/41175867/56761645-198f0900-675b-11e9-8f3c-34a355364a17.png)

**Comment by EleanorRigby** [comment]
@blackramit : It is most likely a DNS issue. Can you check DNS server entry in `bosh.yml`? Refer to this comment: https://github.com/cloudfoundry/bosh-vsphere-cpi-release/issues/30#issuecomment-317828501

**Comment by blackramit** [comment]
I have this in bosh.yml

_networks:
- name: default
  subnets:
  - dns:
    - 8.8.8.8
    gateway: ((internal_gw))
    range: ((internal_cidr))
    static:
    - ((internal_ip))
  type: manual_

I changed it to:

_networks:
- name: default
  subnets:
  - dns:
    - 192.168.10.20
    gateway: ((internal_gw))
    range: ((internal_cidr))
    static:
    - ((internal_ip))
  type: manual_

But i get the same problem.
Is there anyway to get on in interactive mode to the Bosh Director.  When I try to console in I get this screen;

![image](https://user-images.githubusercontent.com/41175867/56761908-c23d6880-675b-11e9-8e5b-e1e3e4b0ace0.png)

**Comment by blackramit** [comment]
Do I have to redeploy the Director Ktchen after changing the bosh.yml?

**Comment by blackramit** [comment]
ALRIGHT!!!  I redeployed Bosh Director after changing the settings in bosh.yml and everything works!

So, to recap; 

1. The ESXi Hosts need to have the DNS setup properly in their physical network config.
2. Cloud-Config needs to have the DNS set properly.
3. And bosh.yml needs to have the DNS setup properly before you deploy the Director.

Just for clarity, has the setup in the Manifest using "-o bosh-deployment/local-dns.yml" and "-v internal_dns=[xxx.xxx.xxx.xxx]" been depricated, or is it still valid to have included?

**Comment by blackramit** [comment]
Guys, just to close out this issue; is this necessary in the setup manifest?

Do we need to be using "-o bosh-deployment/local-dns.yml" and "-v internal_dns=[xxx.xxx.xxx.xxx]"?  Has this been deprecated, or is it still valid to have included?  It didn't seem to do anything in my case and I noticed that the local-dns.yml says it is for legacy support.

**Comment by EleanorRigby** [comment]
`-o` option is to apply any additional ops file you have. `-v` is for any variable that you want to substitute with a value once all ops files have been applied. The ops file can be overridden by other subsequent opsfile and might also not work in certain cases. It is difficult for us to comment why the local dns value did not get picked up. 

The question related to BOSH and its DNS will be better answered on cloudfoundry's slack channel named bosh. See here: https://cloudfoundry.slack.com

**Comment by EleanorRigby** [comment]
Feel free to open the issue if you have more questions.
