### ISSUE TITLE
version bump?

### ISSUE THREAD

**Issue by mxplusb** [cloudfoundry/bosh-vsphere-cpi-release#209]
There's been a bunch of work done since v52, including the support for the custom storage policy support. Can there be a version bump to start consuming and testing some of the new storage policy bits?

**Comment by EleanorRigby** [comment]
Hi @mxplusb, we are working on it. There are issues with SPBM and persistent disk , sans FCD support.

**Comment by mxplusb** [comment]
Hi @EleanorRigby, just wanted to touch base on this topic for a status update. :)

**Comment by EleanorRigby** [comment]
Hi Mike

We are still testing and merging two PR before we cut another release.

The PR in question are human readable names and ability to tag a VM

Tushar

**Comment by mxplusb** [comment]
Thanks!

**Comment by EleanorRigby** [comment]
Release has been cut.
