### ISSUE TITLE
Require/remove defaults for vm_folder, disk_path, and template_folder 

### ISSUE THREAD

**Issue by scottillogical** [cloudfoundry/bosh-vsphere-cpi-release#210]
### Detailed Description
In the docs, https://bosh.io/docs/vsphere-cpi/  it specifies vm_folder and vm_disks and template folder as required

However in the release 
https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/5deb5d3ca86be622befd6cd1078c2758eb9f46ce/jobs/vsphere_cpi/templates/cpi.json.erb#L45 these values have defaults specified
```    
   "vm_folder" => datacenter['vm_folder'] || "BOSH_VMs",
    "template_folder" => datacenter['template_folder'] || "BOSH_Templates",
    "disk_path" => datacenter['disk_path'] || "BOSH_Disks",
```
I think it the bosh init should error if these values are not provided
### Context
I accidentally removed this value and was very confused for a while until I realized there was actually a default and i was missing a setting.  Fairly obvious once I realized it, but it would be nice if for all our directors this was a required setting 
### Implementation
Remove the defaults for these settings and require these be set when you deploy a bosh director

### Complexity
- [x] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by EleanorRigby** [comment]
@scottillogical: Thanks for bringing this to our attention. I am not sure if we are going to remove defaults as it will be breaking change for users relying on it.

We will probably update the documentation to reflect the defaults.

**Comment by julian-hj** [comment]
closing and re-opening to create a tracker story

**Comment by julian-hj** [comment]
https://github.com/cloudfoundry/docs-bosh/pull/749 fixes the docs for this issue.

**Comment by julian-hj** [comment]
PR is merged, so closing this as fixed.
