### ISSUE TITLE
Feature enable_auto_anti_affinity_drs_rules can't handle long deployment names

### ISSUE THREAD

**Issue by damzog** [cloudfoundry/bosh-vsphere-cpi-release#220]
**Describe the bug**
After setting enable_auto_anti_affinity_drs_rules to true deployments with a name exceeding a certain length will fail with:
```
Unknown CPI error ''Unknown'' with message ''''bosh-tenant001-postgresql-service-compilation-0222c0e7-9ff7-4ad4-95ec-8eb9d0564ada'' is invalid or exceeds the maximum number of characters permitted.'' in ''create_vm'' CPI method (CPI request ID: ''cpi-383383'')
```

**To Reproduce**
1. setting enable_auto_anti_affinity_drs_rules to true
2. Create a deployment including some packages to compile. Set the name to <some name probably longer than 30 charactes depending on your directors name>

**CPI Error Log**
```
Date: 2019-06-19 07:58:35 +0000
Additional Request Headers:
SOAPAction: "urn:vim25/6.7"
Accept-Encoding: gzip, deflate
Content-Type: text/xml; charset=UTF-8
Request Body:
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<soapenv:Body><ReconfigureComputeResource_Task xmlns="urn:vim25"><_this type="ClusterComputeResource">domain-c22</_this><spec xsi:type="ClusterConfigSpecEx"><rulesSpec><operation>add</operation><info xsi:type="ClusterAntiAffinityRuleSpec"><enabled>true</enabled><name>bosh-tenant001-postgresql-service-compilation-a2daeec4-518c-4af7-9e4f-2c6136edb08f</name><vm type="VirtualMachine">vm-58981</vm></info></rulesSpec></spec><modify>true</modify></ReconfigureComputeResource_Task></soapenv:Body>
</soapenv:Envelope>
= Response

Status: 200 OK
Response Headers:
Date: Wed, 19 Jun 2019 07:58:35 GMT
Cache-Control: no-cache
Connection: Keep-Alive
Content-Type: text/xml; charset=utf-8
Content-Length: 474
Response Body:
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<ReconfigureComputeResource_TaskResponse xmlns="urn:vim25"><returnval type="Task">task-692975</returnval></ReconfigureComputeResource_TaskResponse>
</soapenv:Body>
</soapenv:Envelope>

[...]

= Request

POST https://xxxxxxxxx/sdk/vimService



Date: 2019-06-19 07:58:35 +0000
Additional Request Headers:
SOAPAction: "urn:vim25/6.7"
Accept-Encoding: gzip, deflate
Content-Type: text/xml; charset=UTF-8
Request Body:
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http:
//www.w3.org/2001/XMLSchema">
<soapenv:Body><RetrievePropertiesEx xmlns="urn:vim25"><_this type="PropertyCollector">propertyCollector</_this><specSet><propSet><type>Task</type><all>false</all><pathSet>info.name</pathSet><pathSet>info.
descriptionId</pathSet><pathSet>info.progress</pathSet><pathSet>info.state</pathSet><pathSet>info.result</pathSet><pathSet>info.error</pathSet><pathSet>info.entity</pathSet></propSet><objectSet><obj type=
"Task">task-692975</obj><skip>false</skip></objectSet></specSet><options></options></RetrievePropertiesEx></soapenv:Body>
</soapenv:Envelope>
= Response

Status: 200 OK
Response Headers:
Date: Wed, 19 Jun 2019 07:58:35 GMT
Cache-Control: no-cache
Connection: Keep-Alive
Content-Type: text/xml; charset=utf-8
Content-Length: 1332
Response Body:
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<RetrievePropertiesExResponse xmlns="urn:vim25"><returnval><objects><obj type="Task">task-692975</obj><propSet><name>info.descriptionId</name><val xsi:type="xsd:string">ClusterComputeResource.reconfigureEx</val></propSet><propSet><name>info.entity</name><val type="ClusterComputeResource" xsi:type="ManagedObjectReference">domain-c22</val></propSet><propSet><name>info.error</name><val xsi:type="LocalizedMethodFault"><fault xsi:type="InvalidName"><name>bosh-tenant001-postgresql-service-compilation-a2daeec4-518c-4af7-9e4f-2c6136edb08f</name></fault><localizedMessage>&apos;bosh-tenant001-postgresql-service-compilation-a2daeec4-518c-4af7-9e4f-2c6136edb08f&apos; is invalid or exceeds the maximum number of characters permitted.</localizedMessage></val></propSet><propSet><name>info.name</name><val xsi:type="xsd:string">ReconfigureComputeResource_Task</val></propSet><propSet><name>info.state</name><val xsi:type="TaskInfoState">error</val></propSet></objects></returnval></RetrievePropertiesExResponse>
</soapenv:Body>
</soapenv:Envelope>

```

**Expected behavior**
Deployment shall shorten the name of silently created objects appropriately while keeping uniqueness.

**Screenshots**
See attachment

**Release Version & Related Info (please complete the following information):**
 - CPI Version 52.1.1
 - BOSH Director Version 268.7.0
 - Stemcell Name & Version 170.76
 - vCenter Version 6.5
 - NSX(T/V) Version (If using)

**Additional context**

**Comment by ktchen14** [comment]
I don't think that there's anything we can do about this. If we choose to trim the name we lose a guarantee of uniqueness for the created DRS anti affinity rule. As such in this instance we recommend that the user choose a shorter name for their deployment and/or instance group.

**Comment by damzog** [comment]
Thanks for the answer ktchen14. I agree there seems to be no trivial way to solve this defect. 

However imho at least error handling should be improved to check name length before sending  a create vm request to vcenter and give a proper error message. Also this kind of constraints should be mentioned in the documentation alongside with e.g. no of vms must not exceed no host in the target cluster.

Further to solve the issue:
- The name of the rule could be a 80 character hash over the calculated name. I guess clashes are very unlikely for this hash size
- You could use the vm name of the first vm of the group (job instance index 0). The vm name is unique. There will be exactly one rule per instance group per deployment.

**Comment by damzog** [comment]
@ktchen14 would you mind to comment?

**Comment by EleanorRigby** [comment]
@damzog: Thanks for suggesting some solutions.

1. We will work on better error handling. 

2. Using vm-name is not possible at all because of the way CPI and BOSH interact.

3. Using an 80 character hash over the calculated name is an option given uniqueness constraints and constraints described below are not violated.

4.
The way naming works currently is by using this string `<director-name>-<deployment-name>-<job-name>`
which helps in setting auto anti-affinity between VMs of the same instance group but not across all instance groups. 

Also, if the name of an instance group is the same, for example, `master` (common name), the current rule name will still distinguish between two different deployments by making two separate rules.

THEREFORE, the naming has to adhere to the same principles if it has to work the same as in prior releases.

5.
```
Also this kind of constraints should be mentioned in the documentation
```
We can add something to vSphere CPI docs on bosh.io  about guidelines on naming and how auto-generated names/ids are created in CPI.

For now, the bug does not seem like a blocker so it might be some time it is picked up for release.

If you need this really soon in a patch release,  feel free to PR a change in.

**Comment by EleanorRigby** [comment]
Another issue with 80 char HASH is losing readability of what rule belongs to what deployment and instance group.

We just introduced human-readable names for VMs in `v53`. Going back to HASH<ed> names, though only for rules will be kind of going backward.

Some of the functions introduced to create unique 80 char human-readable names can be reused to create shortened names for rules too.
