### ISSUE TITLE
Setting Vcenter Storage policy for additional Disks

### ISSUE THREAD

**Issue by sroot1986** [cloudfoundry/bosh-vsphere-cpi-release#225]
### Detailed Description
We are deploying Bosh to VSan currently. And we a default storage policy for our VSan cluster, and also a default policy for the VSan datastore overall. When we deploy to the cluster our bosh vms pick up the storage policy for the cluster as expected but additional data disks that we add only pick up the overall default policy.

Using vsphere cpi v53 we were able to test the below

vcenter.vm_storage_policy_name:
    description: Name of the storage Policy which is applied to a VM and its ephemeral disk.

And this works successfully as intended for the VM OS and ephemeral disk allowing us to select different storage policies for them. Would it be possible to also have this apply to additional data disks that are added to VMs?

### Context
This would allow users to specify a storage policy for their persistent data disks, if they was them to have the same or different policy to the VM OS and ephemeral disks. At the minute its only possible to pick up the datastore default policy it seems.

### Complexity
- [ ] Medium - Change requires some thought, but is relatively isolated

**Comment by arjunsuresh27** [comment]
We are also seeing the same issue, in one of our use case, we need to assign storage policy other than the vsan default to the persistent disks on a Bosh vm. currently the persistent disk will only pick up vsan default storage policy for persistent disks. However, the ephemeral disks can be assigned with the non default/ user defined storage policy on vSAN. We would like to have this feature implemented in Bosh

**Comment by svrc** [comment]
We had a customer situation recently where the lack of persistent disk storage policy may be causing some replication latency issues on the VM for high performance apps.   will take a look at contributing this before EOY

**Comment by julian-hj** [comment]
Closing and re-opening to create a tracker story.
