### ISSUE TITLE
bosh-vsphere-cpi doesn't let you configure GCS bucket as bosh's external blobstore

### ISSUE THREAD

**Issue by ysharma-dev** [cloudfoundry/bosh-vsphere-cpi-release#229]
**Describe the bug**
Configuring bosh director to use GCS bucket as its external blobstore errors out  when running a bosh deploy with the following error:
```
UnknownProperty: Can’t find property ‘agent.blobstore.address’, or ‘blobstore.address’&gt;) (RuntimeError)
```
The bosh manifest pushed by the PCF Operations Manager shows this:
```
properties:
   agent:
     mbus: https://vcap:R_W3SVmDYOELfmDQbFVSzRsmq2epZgS8@0.0.0.0:6868
   blobstore:
     provider: local
     path: “/var/vcap/micro_bosh/data/cache”
```
As you can see from the above manifest snippet, there's is no "agent.blobstore.address"

I believe vsphere cpi does not address in code what to do if GCS is configured. I'm basing this from here: 
https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/d44e1186f9bd850d75bd42549036c80b315cc32a/jobs/vsphere_cpi/templates/cpi.json.erb#L110-L149

**To Reproduce**
1. Configure bosh director to use GCS bucket as its external blobstore.
2. Run bosh deploy (or in this case Apply Changes because I tried configuring Bosh director using Pivotal Cloud Foundry Operations Manager)

**CPI Error Log**
NA - because Bosh director never gets created successfully. The only error available is what I posted above. Please let me know in the comments if there are other ways to grab logs regarding this issue.

From the PCF Operations Manager UI, the Apply change logs shows this:
```
Deploying:
 Building state for instance 'bosh/0':
   Rendering job templates for instance 'bosh/0':
     Rendering templates for job 'vsphere_cpi/e0d9a784159030b0f3165f87b3087a66cc57eb41':
       Rendering template src: cpi.json.erb, dst: config/cpi.json:
         Rendering template src: /home/tempest-web/.bosh/installations/36770d18-0c2f-4be5-6e04-9deb4c1a743c/tmp/bosh-release-job085984372/templates/cpi.json.erb, dst: /home/tempest-web/.bosh/installations/36770d18-0c2f-4be5-6e04-9deb4c1a743c/tmp/rendered-jobs972120918/config/cpi.json:
           Running ruby to render templates:
             Running command: 'ruby /home/tempest-web/.bosh/installations/36770d18-0c2f-4be5-6e04-9deb4c1a743c/tmp/erb-renderer080605373/erb-render.rb /home/tempest-web/.bosh/installations/36770d18-0c2f-4be5-6e04-9deb4c1a743c/tmp/erb-renderer080605373/erb-context.json /home/tempest-web/.bosh/installations/36770d18-0c2f-4be5-6e04-9deb4c1a743c/tmp/bosh-release-job085984372/templates/cpi.json.erb /home/tempest-web/.bosh/installations/36770d18-0c2f-4be5-6e04-9deb4c1a743c/tmp/rendered-jobs972120918/config/cpi.json', stdout: '', stderr: 'fatal: Not a git repository (or any of the parent directories): .git
/home/tempest-web/.bosh/installations/36770d18-0c2f-4be5-6e04-9deb4c1a743c/tmp/erb-renderer080605373/erb-render.rb:189:in `rescue in render': Error filling in template '/home/tempest-web/.bosh/installations/36770d18-0c2f-4be5-6e04-9deb4c1a743c/tmp/bosh-release-job085984372/templates/cpi.json.erb' for vsphere_cpi/0 (line 132: #&lt;TemplateEvaluationContext::UnknownProperty: Can't find property 'agent.blobstore.address', or 'blobstore.address'&gt;) (RuntimeError)
from /home/tempest-web/.bosh/installations/36770d18-0c2f-4be5-6e04-9deb4c1a743c/tmp/erb-renderer080605373/erb-render.rb:174:in `render'
from /home/tempest-web/.bosh/installations/36770d18-0c2f-4be5-6e04-9deb4c1a743c/tmp/erb-renderer080605373/erb-render.rb:200:in `&lt;main&gt;'
':
               exit status 1

Exit code 1
```

**Expected behavior**
Bosh deploy to succeed and external blobstore of the director will be a GCS bucket.

**Screenshots**
NA

**Release Version & Related Info (please complete the following information):**
 - CPI Version **52.1.1**
 - BOSH Director Version **268.6.2**
 - Stemcell Name & Version  **ubuntu-xenial/250.56**
 - vCenter Version - **vSphere Client version 6.7.0.30000**
 - NSX(T/V) Version (If using) - NA
- PCF Operations Manager version - **2.5.6.build.198**

**Additional context**
NA

**Comment by EleanorRigby** [comment]
Thanks for submitting the bug. We will take a look and add it to our story tracker.
