### ISSUE TITLE
Creation of the bosh director in vSphere fails during PCF 2.3 -> 2.4 upgrade

### ISSUE THREAD

**Issue by swagataroy** [cloudfoundry/bosh-vsphere-cpi-release#232]
**Describe the bug**
_bosh create-env_ fails to deploy the directory with cpi error “execution expired”
There are 2 clusters in vCenter. One cluster is dedicated to PCF and another cluster is not.  Ops Manager sits behind a firewall and only has network access to ESX servers in the PCF cluster.  But when running *create_vm* the vSphere CPI is trying to communicate with a ESX server in the Non-PCF cluster ( Datastores are being shared between both clusters ) to upload a file.  Why does the CPI use an ESX server to upload a file that is not in the cluster defined in the directors AZ (pcf01 cluster)

**To Reproduce**

**CPI Error Log**
From the _bosh_init_ Debug logs 
The CPI is trying to upload on the server **kungfu00031** which is not part of the cluster defined in the director's AZ (pcf01 cluster).  This esx host, *kungfu00031* is a member of a Non-PCF cluster in the same vCenter as PCF is using

`I, [2019-08-07T20:39:46.364337 #24018]  INFO -- : Uploading file to https://kungfu00031.abc.test.com/folder/vm-xxxxxxxx/env.json?dsName=OMA00WPH1_Cap_00:01:a9_PCFDEV04...
`

The Error message
`[CLI] 2019/08/07 20:40:50 ERROR - Deploying: Creating instance 'bosh/0': Creating VM: Creating vm with stemcell cid 'sc-b9419e46-37ac-4739-bcb2-35ecc443b456': CPI 'create_vm' method responded with error: CmdError{"type":"Unknown","message":"execution expired","ok_to_retry":false}
`

**Expected behavior**
 CPI should communicate with an ESX server which is in the cluster defined in the director's AZ 

**Screenshots**

**Release Version & Related Info (please complete the following information):**
 - CPI Version 
This happened during an upgrade from Ops Manager version 2.4.build231 (vSphere CPI is *51.1.2*) to
Ops Manager version 2.3.build300 (vSphere CPI is *50.0.4*)
 - BOSH Director Version
after upgrade is 2.3.build300
 - Stemcell Name & Version
 - vCenter Version is 5.5
 - NSX(T/V) Version (If using)

**Additional context**

**Comment by EleanorRigby** [comment]
#233

**Comment by julian-hj** [comment]
This appears to have been fixed by PR #233 and should be in v53.0.2 of the CPI
