### ISSUE TITLE
vSphere CPI bundler is creating directories in Ops Man that are world writable and do not have the sticky bit set

### ISSUE THREAD

**Issue by eoghank** [cloudfoundry/bosh-vsphere-cpi-release#235]
**Describe the bug**
When the vSphere CPI is called to deploy BOSH Director it creates folders here in Ops Man that are world writable and do not have the sticky bit set (/tmp/bundler/home). This is a concern for security teams and our stemcell hardening guides do state that we try to limit world writable directories

**To Reproduce**
1. Setup Ops Man on vSphere
2. Configure BOSH Director and Apply Changes
3. Look for the following folders in Ops Man that are created by the CPI: /tmp/bundler/home

**Expected behavior**
Security teams expect that any world writable directories are either removed or have the sticky bit set
**Screenshots**

**Release Version & Related Info (please complete the following information):**
 - Ops Man 2.5
 - vCenter Version 6.7

**Comment by labrown** [comment]
+1 for support on this issue.  Please address it as soon as possible.

**Comment by ktchen14** [comment]
I suspect that this is from these lines in `cpi.erb`:

```sh
export HOME=~

export BUNDLE_GEMFILE=$BOSH_PACKAGES_DIR/vsphere_cpi/Gemfile
bundle_cmd="${BOSH_PACKAGES_DIR}/ruby-2.4-r4/bin/bundle"

exec $bundle_cmd exec $BOSH_PACKAGES_DIR/vsphere_cpi/bin/vsphere_cpi \
  $BOSH_JOBS_DIR/vsphere_cpi/config/cpi.json
```

That `export HOME=~` line looks extraneous. What's the home directory when Ops Manager is invoking the CPI to deploy the BOSH director?

**Comment by labrown** [comment]
This directory also turns up on the BOSH Director as well.

**Comment by EleanorRigby** [comment]
#245
