### ISSUE TITLE
Error "Request version 'urn:pbm/6.7' and namespace 'urn:pbm' are not supported" runnig create-env

### ISSUE THREAD

**Issue by ichandan16** [cloudfoundry/bosh-vsphere-cpi-release#239]
**Describe the bug**
Hi, I am trying to create a new bosh director on vSphere 5.5. With latest bosh-deployment repo, I am getting below error:

```2019/11/05 21:30:32 ERROR - Error getting CPI info: CPI 'info' method responded with error: CmdError{"type":"Unknown","message":"Request version 'urn:pbm/6.7' and namespace 'urn:pbm' are not supported","ok_to_retry":false} Error getting CPI info: CPI 'info' method responded with error: CmdError{"type":"Unknown","message":"Request version 'urn:pbm/6.7' and namespace 'urn:pbm' are not supported","ok_to_retry":false}```

**To Reproduce**
1. Clone https://github.com/cloudfoundry/bosh-deployment master
2. Execute `bosh create-env`

**CPI Error Log**
```Request version 'urn:pbm/6.7' and namespace 'urn:pbm' are not supported```

**Expected behavior**
Bosh Director should be created and bosh deployments should be successful.

**Screenshots**
[error-stack.log](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/files/3816480/error-stack.log)

**Release Version & Related Info (please complete the following information):**
 - CPI Version - https://bosh.io/d/github.com/cloudfoundry/bosh-vsphere-cpi-release?v=53.0.1

 - BOSH Director Version 
 - Stemcell Name & Version - bosh-stemcell-621.5-vsphere-esxi-ubuntu-xenial-go_agent.tgz
 - vCenter Version - 5.5
 - NSX(T/V) Version (If using)

**Additional context**
Redirect from - https://github.com/cloudfoundry/bosh-deployment/issues/374.

Thanks,
Chandan

**Comment by ktchen14** [comment]
Unfortunately vSphere 5.5 is [out of general support](https://kb.vmware.com/s/article/51491). From the error itself it appears that the CPI is using an API that's only available in vSphere 6.0+. This is the expected behavior.

**Comment by ichandan16** [comment]
Just for the info, which [branch/tag](https://github.com/cloudfoundry/bosh-deployment) should be used if IaaS is vSphere 5.5.

Thanks,
Chandan

**Comment by EleanorRigby** [comment]
Try using tag `v45.1.0`

**Comment by ichandan16** [comment]
@EleanorRigby thank you! I was checking https://github.com/cloudfoundry/bosh-deployment and the vsphere/cpi.yml. None of the available tags has the v45.1.0. The oldest [tagged](https://github.com/cloudfoundry/bosh-deployment/blob/268.0.1/vsphere/cpi.yml) release for bosh-deployment is v50.0.

Thanks,
Chandan
