### ISSUE TITLE
Issue with NSX-T certificate chain incorrectly reported as issue with vCenter certificate chain

### ISSUE THREAD

**Issue by thefluffysysop** [cloudfoundry/bosh-vsphere-cpi-release#247]
Issue with NSX-T certificate chain incorrectly reported as issue with vCenter certificate chain

Bosh Version: 2.7.0.10.0
vSphere CPI Version: 53.0.5
vSphere verison: 6.5
NSX-T verison: 2.4.1

Disclaimer: I am very new to Bosh. I am reporting this on behalf of myself and a far more experienced colleague. 

Building up a greenfield PCF environment. We use a standalone Bosh deployment to help us bootstrap the other underlying infra like Concourse and Minio. 
After Bosh director (standalone) deployment, we proceeded to deploy Concourse. Deployment kept failing on certificate error. 

`Error: Unknown CPI error 'Unknown' with message 'The URL https://<withheld>/sdk/vimService does not have a valid SSL certificate. You may use the manifest property 'vcenter.connection_options.ca_cert' in the global CPI config to set a trusted CA CERTIFICATE, PEM-encoded. Exception: SSL_read: shutdown while in init' in 'delete_vm' CPI method (CPI request ID: 'cpi-945196')`

In the CPI log, we can see its actually referring to an underlying error, that seems to point to NSX. See screenshot below. 

`Peer certificate cannot be authenticated with given CA certificates`

![image](https://user-images.githubusercontent.com/29251599/72976814-94ad4a80-3dd3-11ea-934f-cca5b9549bb4.png)

So this poses a question: Was the issue with vSphere vCenter Certs, or with NSX-T Manager Certs?
In this environment, the vSphere vcenter certs where self-signed, and the NSX-T certs where CA signed. 

Up to this point, and in a different environment that has been running for over a year, the CPI config contained the CA Root Cert.  
Additionally, the CA Root Cert, intermediate CA Cert, and NSX-T Manager Cert, where all included in the Bosh Deployment trusted certs list.  
It was expected the same configuration would work fine in building this new environment. 

FYI, the two places we are configuring this is: 

/cloud_provider/properties/vcenter/nsxt/ca_cert
/instance_groups/name=default/bosh/properties/vcenter/nsxt/ca_cert

We first tried replacing the CA Root Cert, with the actual NSX Manager (vip) Cert. 

This did not change the behavior, we got the same error. 

We then tried running without any Cert defined in the CPI Config. This resulted in.. a mess.

 (our conclusion is that the CPI seems to totally ignore the Bosh trusted cert list). 

We then added the entire CA chain to the CPI config. This seemed to solve the problem. We did not change another other config.

Additionally, the way the type of cert error is reported, needs improvement. 
In the #Bosh channel in CF Slack, in my thread, Conor Nosal  summarized it as follows: 

> The message might be overly specific. It looks like all SSL errors are caught and assumed to be "invalid cert" (https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/master/src/vsphere_cpi/lib/cloud/vsphere/base_http_client.rb#L82) but your stack shows an SSL_read error, not a handshake error.

So in any case, 
1. the CPI is incorrectly reporting a certificate error with the wrong thing.  It incorrectly point you do an issue with the vCenter cert when the issue is (probably) NSX-T cert. 
2. It seems to treat each error as 'invalid vert' 
3. If it is indeed the case that the CPI config now requires the entire cert chain in PEM format, this is not documented. ( in https://bosh.io/docs/vsphere-cpi/#global )

**Comment by EleanorRigby** [comment]
Did you populate this variable in CPI config `vcenter.connection_options.ca_cert`?

**Comment by thefluffysysop** [comment]
Yes, it had our vCenter self-signed cert in it

**Comment by dbarkelew** [comment]
Does the trust CA chain for the NSX-T certificate use a cross signed CA to build the trust?

**Comment by thefluffysysop** [comment]
> Does the trust CA chain for the NSX-T certificate use a cross signed CA to build the trust?

I do not believe so, it is a single chain with 1 root CA, and 1 subordinate/intermediate CA
Where could I double-check this?

**Comment by dbarkelew** [comment]
Normally the easiest way to check is to ask the person who issued the certificate to you if the CA is cross signed or not. If you are using a public CA, this is more likely. If you are using a private CA, not as likely.

**Comment by julian-hj** [comment]
@thefluffysysop is this issue still reproducible? From what I can see in the screenshotted logs, it appears to me that there were two separate errors connecting to vSphere and NSX-T manager.

Is it possible that the bosh director lost connectivity? The vSphere failure is reporting `SSLRead: shutdown while in init`.

**Comment by julian-hj** [comment]
Closing this, but feel free to re-open if it is reproduced.
