### ISSUE TITLE
No property exposed to tune snapshot replication timeout

### ISSUE THREAD

**Issue by pivotal-todd-robbins** [cloudfoundry/bosh-vsphere-cpi-release#253]
### Detailed Description

There is no way to tune snapshot creation timeout. It is hardcoded. If there are VM's with large snapshots that need to be replicated across slow networks/datastores then this can lead to CPI errors:

`E, [2020-02-03T20:42:16.173402 #23088] ERROR -- [req_id cpi-101060]: Error in creating vm: The object[s] '<[Vim.VirtualMachine] vm-39068>' should have the following properties: ["snapshot"]`

### Context

After cloning/replicating the stemcell on a datastore , CPI creates a snapshot on the stemcell (needed for link cloning)
This snapshot is missing from the replicated stemcell.
Usually CPI waits ~256 seconds to allow vSphere to create a snapshot post replication.

### Possible Implementation
Expose a property in vsphere CPI which allows configuration of snapshot replication timeout.

### Complexity
Low/Medium

**Comment by julian-hj** [comment]
Closing, then re-opening to create an issue in our tracker backlog. We might also just consider extending the existing timeout.
