### ISSUE TITLE
PKS cluster creation Failed to apply NSX properties to VM 'vm-xxxxxx'  with error: The object was modified by

### ISSUE THREAD

**Issue by eveane** [cloudfoundry/bosh-vsphere-cpi-release#256]
**Describe the bug**
cluster creation fail on one of the node where the it fail to attach the logical port :+1: 
`I, [2020-02-18T20:29:07.237240 #23841]  INFO -- [req_id cpi-749191]: Failed to apply NSX properties to VM 'vm-0353af02-7815-48d8-be12-42edad9d0097' with error: The object was modified by somebody else. Please retry.`

**To Reproduce**
1. Have a vSphere environment with NSX-T backend
2. deploying new clusters or scaling new clusters on the same vsphere backend using the same NS-group
3. aim to have the operation to be almost simultaneously (in this occurrence we have 1 ms difference between two NSX-T API calls adding a new members to the same NS-Group)

**CPI Error Log**
```
I, [2020-02-18T20:29:01.441195 #23841] INFO – [req_id cpi-749191]: LogicalPorts found for vm 'vm-0353af02-7815-48d8-be12-42edad9d0097': ["3bde2632-2054-4d9a-84fe-21afb12d2514", "3bde2632-2054-4d9a-84fe-21afb12d2514"]'
I, [2020-02-18T20:29:01.441341 #23841] INFO – [req_id cpi-749191]: Adding LogicalPorts: ["3bde2632-2054-4d9a-84fe-21afb12d2514", "3bde2632-2054-4d9a-84fe-21afb12d2514"] to NSGroup '41630f5c-af77-422e-8d89-4c1d326965eb'
I, [2020-02-18T20:29:07.237240 #23841] INFO – [req_id cpi-749191]: Failed to apply NSX properties to VM 'vm-0353af02-7815-48d8-be12-42edad9d0097' with error: The object was modified by somebody else. Please retry.
I, [2020-02-18T20:29:07.237397 #23841]  INFO -- [req_id cpi-749191]: Deleting VM 'vm-0353af02-7815-48d8-be12-42edad9d0097'...
```

NSX Logs from vmware loginsight

There are 2 distinct and concurrent requests to update the NSgroup with a logical port at this time
`ReqID=6ac74828-26a3-40d3-8bc0-41828e1255a7 Add logical switch port 3bde2632-2054-4d9a-84fe-21afb12d2514 to NSGroup 41630f5c-af77-422e-8d89-4c1d326965eb"<182>1 2020-02-18T20:29:07.067Z nsxmanager0701 NSX 5453 GROUPING [nsx@6876 comp=""nsx-manager"" level=""INFO"" reqId=""6ac74828-26a3-40d3-8bc0-41828e1255a7"" subcomp=""manager"" username=""admin""] Adding members [[LogicalPort.id EQUALS 3bde2632-2054-4d9a-84fe-21afb12d2514]] to the NSGroup NSGroup/41630f5c-af77-422e-8d89-4c1d326965eb",1f4fdc4f-86e1-45a7-affa-fc1202c2451a,491,29226108,nsxt-api-log,NSX,,nsx-manager,,v4_2896a0e5,/var/log/syslog,nsxmanager0701,INFO,GROUPING,22,6,5453,6ac74828-26a3-40d3-8bc0-41828e1255a7,,XXX.XXX.XXX.XXX,manager,2020-02-18 20:29:07.067,admin,CMP-Str-Prod-01,CMP,esx0027.infra.net,,nsx-manager,,,manager,admin,vm-436441,ESC_CM02_CMP - vcenter.infra.net,1fd07082-39fb-4795-8941-aa1e33eb3c72,c38586f2-c46e-460d-b573-a7b7004c4b96
`
`ReqID=2f2f17d-6c8a-4342-b105-7e4d72e2b138 Add logical switch port 6cf87229-ad0b-4106-bff5-4b79449803bf to NSGroup 41630f5c-af77-422e-8d89-4c1d326965eb"<182>1 2020-02-18T20:29:07.068Z nsxmanager0701 NSX 5453 GROUPING [nsx@6876 comp=""nsx-manager"" level=""INFO"" reqId=""52f2f17d-6c8a-4342-b105-7e4d72e2b138"" subcomp=""manager"" username=""admin""] Adding members [[LogicalPort.id EQUALS 6cf87229-ad0b-4106-bff5-4b79449803bf]] to the NSGroup NSGroup/41630f5c-af77-422e-8d89-4c1d326965eb",1f4fdc4f-86e1-45a7-affa-fc1202c2451a,492,29226108,nsxt-api-log,NSX,,nsx-manager,,v4_2896a0e5,/var/log/syslog,nsxmanager0701,INFO,GROUPING,22,6,5453,52f2f17d-6c8a-4342-b105-7e4d72e2b138,,XXX.XXX.XXX.XXX,manager,2020-02-18 20:29:07.068,admin,CMP-Str-Prod-01,CMP,esx0027.infra.net,,nsx-manager,,,manager,admin,vm-436441,ESC_CM02_CMP - vcenter.infra.net,1fd07082-39fb-4795-8941-aa1e33eb3c72,c38586f2-c46e-460d-b573-a7b7004c4b96`

One request succeeds (200) and one has a conflict error (409)

also they come with only 1 ms interval:
2020-02-18T20:29:07.067
2020-02-18T20:29:07.068

HTTP 200 - success
`"2020-02-18T20:29:07.220Z - ""POST /nsxapi/api/v1/ns-groups/41630f5c-af77-422e-8d89-4c1d326965eb?action=ADD_MEMBERS HTTP/1.1"" 200 36307 290 288",eb573cc0-727b-46d1-8fbc-f172556cc216,426,56102960,nsxt-proton,,,,,v4_9959dd40,/var/log/proton/localhost_access_log.txt,nsxmanager0701,,,,,,,,XXX.XXX.XXX.XXX,,2020-02-18 20:29:07.220,,CMP-Str-Prod-01,CMP,esx0027.infra.net,,,,,,,vm-436441,ESC_CM02_CMP - vcenter.infra.net,1fd07082-39fb-4795-8941-aa1e33eb3c72,c38586f2-c46e-460d-b573-a7b7004c4b96`

HTTP 409 - conflict
`"2020-02-18T20:29:07.197Z - ""POST /nsxapi/api/v1/ns-groups/41630f5c-af77-422e-8d89-4c1d326965eb?action=ADD_MEMBERS HTTP/1.1"" 409 902 5777 5777",eb573cc0-727b-46d1-8fbc-f172556cc216,425,56102960,nsxt-proton,,,,,v4_9959dd40,/var/log/proton/localhost_access_log.txt,nsxmanager0701,,,,,,,,XXX.XXX.XXX.XXX,,2020-02-18 20:29:07.197,,CMP-Str-Prod-01,CMP,esx0027.infra.net,,,,,,,vm-436441,ESC_CM02_CMP - vcenter.infra.net,1fd07082-39fb-4795-8941-aa1e33eb3c72,c38586f2-c46e-460d-b573-a7b7004c4b96`

The request to add LSP bde2632-2054-4d9a-84fe-21afb12d2514 to NSGroup '41630f5c-af77-422e-8d89-4c1d326965eb' did not succeed and hence the PKS logging.

**Expected behavior**
Upon a failure, would retry "Adding LogicalPorts:" before deleting the VM

**Screenshots**

**Release Version & Related Info (please complete the following information):**
 - PKS 1.6.1
 - CPI Version vSphere CPI  53.0.7
 - BOSH Director v2.7.9
 - vCenter 6.7 U2
 - NSX-T 2.5.0

**Comment by dj-jadeja** [comment]
Hi Sanika, 

Customer is looking for update on progress of the fix. Can you provide with some update here?

Thank you

**Comment by SanikaGawhane** [comment]
This is not picked up yet and will be prioritized in coming sprints.

**Comment by julian-hj** [comment]
This issue appears to be fixed by [this commit](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/commit/55acb239dd51efa1e54c595abe236c3e96274e5b) which is included in v54 of the vSphere CPI
