### ISSUE TITLE
check on ip conflict uses vm inventory instead of bosh provisioning

### ISSUE THREAD

**Issue by JCL38-ORANGE** [cloudfoundry/bosh-vsphere-cpi-release#257]
**Describe the bug**
I observe that ip conflict detector component is based on dynamic vms inventory (call stack  
vm_creator.rb -> ip_conflict_detector.rb -> vcenter_client.rb -> ruby_vim_sdk.rb).
I expect to have a ip conflict detector based on the bosh provisioning performed in vsphere.

**To Reproduce**
0. Given two networks : one private and one public
1. Create a VM with two NICs (one in a private network and one in a public network called VIP)
2. Create two VMs called proxy with one NIC for each (in the public network)
3. Setup VRRP (ha-proxy bosh release) between proxy VMs. The VRRP used the VIP allocated at step one. So one of the proxy (MASTER) is using the VIP (anonymous fashion).
4. Execute a bosh recreate on the VM which hold the two NICs.
5.The recreate will fail because the CPI will query the VM inventory (https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.SearchIndex.html#findByIp) and the VIP will be returned as used by one of the proxy VM (MASTER). 

**CPI Error Log**
Detected IP conflicts with other VMs on the same networks: vm-ece4010c-6ab4-4a47-92cf-5414d6030e19 on network vxw-dvs-27-virtualwire-78-sid-7029-VXS_CFY_MP_Int_S3_2 with ip 10.118.42.200

**Expected behavior**
I expect to have a parameter which allows me to disable this control since it is not a bosh concern.

**Release Version & Related Info (please complete the following information):**
 - CPI Version - 52.1
 - BOSH Director Version - 270.8.0
 - Stemcell Name & Version - bosh-vsphere-esxi-ubuntu-xenial-go_agent/bosh-stemcell-456.84-vsphere-esxi-ubuntu-xenial-go_agent.tgz

**Comment by EleanorRigby** [comment]
@JCL38-ORANGE :  We are looking into the issue and taking ktchen14's comment into account.

Can you also provide us some more info:
 - Are you consuming CPI via ops manager?
 - What's the full version of CPI being consumed `52.1.0` or `52.1.x`

**Comment by JCL38-ORANGE** [comment]
Hello,

Thanks for your quick answer.
We are not consuming CPI via OPS Manager.
The CPI version is : 52.1.0

Best regards,
Jean-Christophe.

**Comment by EleanorRigby** [comment]
Please track the progress here https://www.pivotaltracker.com/story/show/171660267

**Comment by JCL38-ORANGE** [comment]
Hello,

I will get back to you with the reason.
If you deliver it in v53, do you have a schedule for that ?
Thanks and regards,
Jean-Christophe.

**Comment by JCL38-ORANGE** [comment]
Hello,

We bump latest CPI release v53.0.9 in our side.
Could we expect a release in the next coming weeks based on v53 release ?
Thanks and regards,
Jean-Christophe.

**Comment by ktchen14** [comment]
@JCL38-ORANGE We can’t commit to a particular timeline for the delivery of a feature. At this time we’re still discussing what the best solution will be.

If you need this quickly you can stub out the IPConflictDetector and rebuild the CPI.

**Comment by JCL38-ORANGE** [comment]
@ktchen14, thanks for your answer.
Regards,
Jean-Christophe.

**Comment by julian-hj** [comment]
From what I can establish, this issue was fixed by the removal of ip_conflict_detector in v54 of the CPI. Please feel free to re-open as necessary.
