### ISSUE TITLE
CPI doesn't use TCP Keepalive socket option which results in unnecessary long 4h timeouts

### ISSUE THREAD

**Issue by mayrstefan** [cloudfoundry/bosh-vsphere-cpi-release#280]
**Describe the bug**
We have an environement with a firewall between director and vCenter. This firewall removes connections from its internal state table if they have been idle for 10 minutes. Packets that do not match a valid connection are dropped (not rejected) by the firewall.
We found that sometimes we have deployment issues that look like a hanging call to AquireGenericServiceTicket which takes up to 4 hours until it times out
```
I, [2020-11-11T01:29:01.504860 #20373]  INFO -- [req_id cpi-389242]: Trying to upload file to Datastore through Host System
I, [2020-11-11T01:29:02.586813 #20373]  INFO -- [req_id cpi-389242]: Acquiring generic service ticket for URL: https://esxi123.example.com/folder/vm-a02ca2e1-3232-4e46-b2b2-9cf89469226b/env.json?dsName
=PCF-datastore-123 and Method: httpPut
D, [2020-11-11T01:29:02.586984 #20373] DEBUG -- [req_id cpi-389242]: Running method 'AcquireGenericServiceTicket'...
W, [2020-11-11T05:29:02.595149 #20373]  WARN -- [req_id cpi-389242]: Error running method 'AcquireGenericServiceTicket'. Failed with 'HTTPClient::ReceiveTimeoutError: execution expired'`
```
In the vCenter logs we found timeouts to the esxi host after 15 minutes. So the CPI should get a response from the vCenter after 15 minutes. If we raise the firewall timeout we get what we expected
```
D, [2020-11-13T10:09:39.180131 #15937] DEBUG -- [req_id cpi-223098]: Running method 'AcquireGenericServiceTicket'...
W, [2020-11-13T10:25:10.137432 #15937]  WARN -- [req_id cpi-223098]: Error running method 'AcquireGenericServiceTicket'. Failed with message 'An error occurred while communicating with the remote host.'.
W, [2020-11-13T10:25:11.138789 #15937]  WARN -- [req_id cpi-223098]: Retrying method 'AcquireGenericServiceTicket', 1 attempts so far...
I, [2020-11-13T10:25:11.256549 #15937]  INFO -- [req_id cpi-223098]: Uploading file to https://esxi123.example.com/folder/vm-582a50bc-2e9d-481f-869f-56cf0edd4279/env.json?dsName=PCF_datastore-123...
I, [2020-11-13T10:25:11.286207 #15937]  INFO -- [req_id cpi-223098]: Successfully uploaded file.
```

**To Reproduce**
We could not reproduce this on purpose. But we found this happens more often in environements with less load like our sandbox installation.

**CPI Error Log**
see above

**Expected behavior**
Raising the firewall timeout should not be necessary if TCP Keepalive would be enabled on the socket. Operating system keepalive seetings are already tuned to match the firewall timeouts. We expect the CPI to use the TCP SO_KEEPALIVE option.

**Release Version & Related Info (please complete the following information):**
 - CPI Version: 54.1.0
 - vCenter Version: 6.7
 - NSX(T/V) Version (If using): not used

**Additional context**
I guess that https://kb.vmware.com/s/article/67529 is releated. If I understand the article correctly the keepalive socket option was enabled by vCenter in earlier versions. When we upgraded to vCenter 6.7 we lost this feature and now it is up to the CPI to keep the connection alive.

**Comment by ktchen14** [comment]
Fixed in v54.1.1.
