### ISSUE TITLE
vSAN large scale environment HA alarms during stemcell changes

### ISSUE THREAD

**Issue by thelangley** [cloudfoundry/bosh-vsphere-cpi-release#284]
**Summary of issue**
When Bosh is doing many parallel update tasks (usually diego-cells), at least one false HA event is triggered in the cluster. This only happens on vSAN based environments with a lot of VMs in the Bosh deployment. The only way to remove the error is disable HA, re-enable HA.

VMware engineering have acknowledged the feature.

**To Reproduce**
- Use vCenter 6.5 to 6.7 u3l, ESXi 6.5 -> 6.7 November 2020 patch levels
- Ensure HA is enabled on the cluster
- Use cf-deployment with 260+ diego_cells
- Look in vCenter at cluster info during the process. Is there an alarm that goes off to say something like `0 VMs being restarted, 1 VMs waiting for a retry, 0 VMs waiting for resources, 0 inaccessible vSAN VMs`?

**CPI Error log**
Interestingly no CPI error. As the IaaS layer is responding to Bosh to say "destroy complete", "clone complete", "edit vm complete" with the expected status code. The bosh-vsphere-cpi will just carry on and complete successfully. There's no real HA event kicking off but it does set off the alarms.

This is really an issue at a ESXi fdm (HA agent) level as acknowledged by VMware fdm engineering team.

**Release Version**
As this issue has occurred for years, it's occurred on many versions. The bug exists in fdm.

bosh-vsphere-cpi-release: 53.0.9, 54.1.1
bosh: 270.10.0, 271.2.0
stemcell: 621.90, 621.92, 621.101
ESXi: 6.5/6.7
vCenter: 6.5/6.7
NSX-v: 6.3.5, 6.4.6a, 6.4.8

**Detail from VMware engineering/background**
We've been using vSAN on ESXi 6.5/6.7 for a few years now. It's Dell HCI so these are vendor compliant, verified software/firmware versions.

We've raised several tickets with VMware about this over the years and we've got furthest with the current one. Below is the detail from the ticket.

```
I have feedback from Engineering and they have highlighted that the sequence of events is as follows:

- VM is powered off from VC - FDM marks it for unprotect
- VM still exists in the protected list for fdm
- VM is deleted from VC
- FDM gets the VM deletion update 
- FDM removes the VM from its inventory
- However, the VM is still in the protection list which leads to this VM being discovered and re-added to the inventory
- FDM tries to place the VM and the event is generated

We have feedback from Engineering and they have highlighted that there is a difference in behaviour for FDM in these scenarios, as the way FDM module maintains the protection list is different for vSAN and non-VSAN. 

In case of non-vSAN, the protectedlist is a physical file, with a lock held on this file. In case of vSAN, the protectedlist stored in a sort of vSAN HA_Metadata, so potentially there could be a delay in the unprotect request, when compared to non-vSAN environment.

However, Engineering have again highlighted that they would recommend to introduce a progressive delay into the automation process, before the deleteVM() method, then that would assist Engineering in identifying the source issue. This would then facilitate them in modifying the unprotect/protect process to ensure that it is more efficient on vSAN environments.

Engineering have previously highlighted that don't expose the unprotect property of the VM to the clients, so they recommend to try starting with a 10 second delay and then review the deployment and increase the delay if required.
```

So there's no API call that we can do to specifically unprotect the VM on vSAN based envs. The only thing that they're saying to do is inject a `sleep 10` in https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/v54.1.1/src/vsphere_cpi/lib/cloud/vsphere/cloud.rb#L469 as far as I can see. However, this would slow down non-vSAN based envs or much smaller vSAN envs that are not impacted by this HA feature. Maybe an ops file could be used which injects a var (something like `vsan_scale_env`:`True`) which could enable the delay. Default behaviour would be the same as today.

Just to be clear, this is just to work around VMware fdm on larger scale vSAN based environments.

**Comment by cunnie** [comment]
We're closing and re-opening this issue to generate a tracker story in our internal tracking system.

**Comment by thelangley** [comment]
Still an issue, bug unfixed by VMware. workaround still required

**Comment by julian-hj** [comment]
@thelangley Can you have a look at PR #301 and let us know if it looks like it will fix this issue, as far as you understand it?

We are hoping to avoid both:
- Adding a "sleep" on every VM deletion and
- Adding new configuration that needs to be configurable through commercial distributions

So, we took the approach of only adding a delay when the deleted VM is using a vSAN datastore, and HA is enabled on the compute cluster. Since HA is disabled by default, we're hoping that will reduce the impact of the change for smaller deployments.

**Comment by thelangley** [comment]
This looks wonderful and meets all of our wants.

I haven't tested your commits but they look very reasonable. I'll try to build a release from your commit and put it into our lab today.

**Comment by thelangley** [comment]
It looks like it works as described. I've recreated an entire deployment and the error hasn't recurred.

Happy for these changes to be merged, a release to be cut and my issue closed.

Thanks again @julian-hj

**Comment by julian-hj** [comment]
Awesome. Thanks @thelangley for the fast turnaround. We'll get this merged shortly.

**Comment by julian-hj** [comment]
This is fixed in [v66](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/releases/tag/v66)
