### ISSUE TITLE
Support for NSX-T Policy API

### ISSUE THREAD

**Issue by miro-grapeup** [cloudfoundry/bosh-vsphere-cpi-release#285]
## Support Question
I would like to know what is the current state of Policy-API support? I can see there were two PRs in the past:
https://github.com/cloudfoundry/bosh-vsphere-cpi-release/pull/212
https://github.com/cloudfoundry/bosh-vsphere-cpi-release/pull/217
but they were closed. Is there any plan to support NSX-T policy api? Right now it seems to be not possible to use Bosh with such objects due to error if you are note an EnterpriseAdmin:
```
Principal 'svc-account@local' with role '[lb_admin, auditor, security_engineer, network_engineer]' attempts to delete or modify an object of type LoadBalancerPool it doesn't own. (createUser=nsx_policy, allowOverwrite=true)"
```
or if you are an EnterpriseAdmin it is not visible in the PolicyAPI (changes are visible only in the ManagerAPI).

---

You can also reach out to us via:

* Slack: http://cloudfoundry.slack.com/messages/bosh-cpi-dev

**Comment by cunnie** [comment]
Hi @miro-grapeup ,

Thanks for your insights and expertise—your contributions have made the CPI much better!

We believe that the Policy API is fully implemented at this point, so we're closing this ticket, but if there's anything we've overlooked, please don't hesitate to open a new ticket.
