### ISSUE TITLE
Support add "bosh/id" tags for SegmentPort in Policy API mode

### ISSUE THREAD

**Issue by ydp** [cloudfoundry/bosh-vsphere-cpi-release#291]
### Detailed Description

TKGI leverage the "bosh/id" tags in LogicalPort in MP API side to find the correct VM, we would like to have the same feature supported in Policy API mode.

{“scope”: “bosh/id”, “tag”: “xxxxxxx”}

This feature in MP API is here: https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/master/src/vsphere_cpi/lib/cloud/vsphere/nsxt_provider.rb#L200 

### Context

TKGI will distinguish different instance group to do some task, so we need to find the correct vm in side bosh job, this is the approach to find the vm.

### Possible Implementation

Looks like this old branch already have this feature: https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/ta-policy-bundle/src/vsphere_cpi/lib/cloud/vsphere/nsxt_policy_provider.rb#L154 

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by mariash** [comment]
Please see the latest release https://github.com/cloudfoundry/bosh-vsphere-cpi-release/releases/tag/v57 It should have this feature.
