### ISSUE TITLE
ability to disable Antiaffinity and DRS rules on the vsphere CPI 

### ISSUE THREAD

**Issue by arjunra22** [cloudfoundry/bosh-vsphere-cpi-release#292]
### Detailed Description

We are trying to deploy CFCR using bosh director on Vmware  and while deploying the kubernetes part the Vsphere CPI errors out due to insufficient privledges by Vcenter user for creating DRS rules . 

### Context

WE would like to disable Anti affinity & any DRS rules as we do not intend to use these on our TEst / Dev platform .

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [x] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by arjunra22** [comment]
Part of the CPI debug logs is below .


I, [2021-04-21T18:14:36.155658 #30393]  INFO -- [req_id cpi-809405]: Successfully uploaded file.
D, [2021-04-21T18:14:36.205278 #30393] DEBUG -- [req_id cpi-809405]: Running method 'ReconfigVM_Task'...
D, [2021-04-21T18:14:36.226035 #30393] DEBUG -- [req_id cpi-809405]: Starting task 'VirtualMachine.reconfigure'...
D, [2021-04-21T18:14:37.255020 #30393] DEBUG -- [req_id cpi-809405]: Finished task 'VirtualMachine.reconfigure' after 1.028845338 seconds
D, [2021-04-21T18:14:37.285499 #30393] DEBUG -- [req_id cpi-809405]: Creating DRS rule attribute
D, [2021-04-21T18:14:37.285646 #30393] DEBUG -- [req_id cpi-809405]: Creating DRS rule attribute: drs_rule
D, [2021-04-21T18:14:37.285783 #30393] DEBUG -- [req_id cpi-809405]: Running method 'AddCustomFieldDef'...
W, [2021-04-21T18:14:37.291939 #30393]  WARN -- [req_id cpi-809405]: Error running method 'AddCustomFieldDef'. Failed with message 'Permission to perform this operation was denied.'.
I, [2021-04-21T18:14:37.292337 #30393]  INFO -- [req_id cpi-809405]: Permission to perform this operation was denied. - /var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335                                         /lib/cloud/vsphere/sdk_helpers/retryable_stub_adapter.rb:75:in `block in invoke_method'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/retryer.rb:9:in `block in try'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/retryer.rb:8:in `times'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/retryer.rb:8:in `try'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/sdk_helpers/retryable_stub_adapter.rb:33:in `invoke_method'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/ruby_vim_sdk/vmodl/managed_object.rb:13:in `invoke_method'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/ruby_vim_sdk/vmodl/managed_object.rb:45:in `block (3 levels) in finalize'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/drs_rules/vm_attribute_manager.rb:19:in `create'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/drs_rules/drs_rule.rb:53:in `tag_vm'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/drs_rules/drs_rule.rb:19:in `add_vm'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/vm_creator.rb:299:in `create_drs_rules'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/vm_creator.rb:198:in `block in create'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/vm_creator.rb:26:in `each'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/vm_creator.rb:26:in `create'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/cloud.rb:362:in `block in create_vm'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/vendor/bundle/ruby/2.6.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/cloud.rb:307:in `create_vm'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/2.6.0/forwardable.rb:230:in `create_vm'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/vendor/bundle/ruby/2.6.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in `public_send'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/vendor/bundle/ruby/2.6.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in `run'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:48:in `<top (required)>'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `load'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `kernel_load'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:476:in `exec'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:30:in `dispatch'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:24:in `start'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/exe/bundle:46:in `block in <top (required)>'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/exe/bundle:34:in `<top (required)>'
/var/vcap/packages/ruby-2.6.5-r0.29.0/bin/bundle:23:in `load'
/var/vcap/packages/ruby-2.6.5-r0.29.0/bin/bundle:23:in `<main>'
I, [2021-04-21T18:14:37.292480 #30393]  INFO -- [req_id cpi-809405]: Deleting vm: master_test_4737a6a2fe21
D, [2021-04-21T18:14:37.292640 #30393] DEBUG -- [req_id cpi-809405]: Running method 'FindByInventoryPath'...
D, [2021-04-21T18:14:37.297913 #30393] DEBUG -- [req_id cpi-809405]: Running method 'CreateContainerView'...
I, [2021-04-21T18:14:37.711467 #30393]  INFO -- [req_id cpi-809405]: VM 'master_test_4737a6a2fe21' is already powered off, skipping power off task.
I, [2021-04-21T18:14:37.833970 #30393]  INFO -- [req_id cpi-809405]: Cleaning current agent env from vm 'master_test_4737a6a2fe21'
D, [2021-04-21T18:14:37.904557 #30393] DEBUG -- [req_id cpi-809405]: Running method 'DeleteDatastoreFile_Task'...
D, [2021-04-21T18:14:37.925732 #30393] DEBUG -- [req_id cpi-809405]: Starting task 'FileManager.deleteFile'...
D, [2021-04-21T18:14:38.955303 #30393] DEBUG -- [req_id cpi-809405]: Finished task 'FileManager.deleteFile' after 1.029414652 seconds
D, [2021-04-21T18:14:38.955505 #30393] DEBUG -- [req_id cpi-809405]: Running method 'DeleteDatastoreFile_Task'...
D, [2021-04-21T18:14:38.978450 #30393] DEBUG -- [req_id cpi-809405]: Starting task 'FileManager.deleteFile'...
D, [2021-04-21T18:14:40.015378 #30393] DEBUG -- [req_id cpi-809405]: Finished task 'FileManager.deleteFile' after 1.03675545 seconds
D, [2021-04-21T18:14:40.015617 #30393] DEBUG -- [req_id cpi-809405]: Running method 'Destroy_Task'...
D, [2021-04-21T18:14:40.038931 #30393] DEBUG -- [req_id cpi-809405]: Starting task 'VirtualMachine.destroy'...
D, [2021-04-21T18:14:41.065203 #30393] DEBUG -- [req_id cpi-809405]: Finished task 'VirtualMachine.destroy' after 1.026100913 seconds
I, [2021-04-21T18:14:41.065369 #30393]  INFO -- [req_id cpi-809405]: Deleted vm: master_test_4737a6a2fe21
E, [2021-04-21T18:14:41.065541 #30393] ERROR -- [req_id cpi-809405]: Error in creating vm: Permission to perform this operation was denied., Backtrace - /var/vcap/data/packages/vsphere_cpi/f642f77                                         6c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/sdk_helpers/retryable_stub_adapter.rb:75:in `block in invoke_method'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/retryer.rb:9:in `block in try'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/retryer.rb:8:in `times'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/retryer.rb:8:in `try'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/sdk_helpers/retryable_stub_adapter.rb:33:in `invoke_method'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/ruby_vim_sdk/vmodl/managed_object.rb:13:in `invoke_method'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/ruby_vim_sdk/vmodl/managed_object.rb:45:in `block (3 levels) in finalize'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/drs_rules/vm_attribute_manager.rb:19:in `create'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/drs_rules/drs_rule.rb:53:in `tag_vm'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/drs_rules/drs_rule.rb:19:in `add_vm'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/vm_creator.rb:299:in `create_drs_rules'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/vm_creator.rb:198:in `block in create'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/vm_creator.rb:26:in `each'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/vm_creator.rb:26:in `create'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/cloud.rb:362:in `block in create_vm'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/vendor/bundle/ruby/2.6.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/cloud.rb:307:in `create_vm'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/2.6.0/forwardable.rb:230:in `create_vm'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/vendor/bundle/ruby/2.6.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in `public_send'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/vendor/bundle/ruby/2.6.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in `run'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:48:in `<top (required)>'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `load'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `kernel_load'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:476:in `exec'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:30:in `dispatch'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:24:in `start'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/exe/bundle:46:in `block in <top (required)>'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/2cbb5fc3753204d9e0b92baf7640a341ee7bc9e1/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/exe/bundle:34:in `<top (required)>'
/var/vcap/packages/ruby-2.6.5-r0.29.0/bin/bundle:23:in `load'
/var/vcap/packages/ruby-2.6.5-r0.29.0/bin/bundle:23:in `<main>'
I, [2021-04-21T18:14:41.065944 #30393]  INFO -- [req_id cpi-809405]: Finished create_vm in 27.5 seconds
D, [2021-04-21T18:14:41.066546 #30393] DEBUG -- [req_id cpi-809405]: Running method 'Logout'...
Rescued Unknown: Permission to perform this operation was denied.. backtrace: /var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/sdk_helpers/retryable_s                                         tub_adapter.rb:75:in `block in invoke_method'
/var/vcap/data/packages/vsphere_cpi/f642f776c820d4ab9e6801ac799ef159cc917335/lib/cloud/vsphere/retryer.rb:9:in `block in try'
/var/vcap/data/packages/vsphere_cpi/f642

**Comment by moleske** [comment]
Are you setting `enable_auto_anti_affinity_drs_rules`?  It defaults to false and prevents using DRS Rules as described in the [docs](https://bosh.io/docs/vsphere-cpi/#global)

If that is indeed set to false, what version of the CPI are you using?  We would also want to see your bosh director manifest and your deployment manifest.

**Comment by arjunra22** [comment]
@moleske  Thanks for your reply , i was able to solve it but editing the cc-vm-types.yml  and removing the whole datacenter section or if you chose to keep it then you can use **disable_drs [Boolean, Optional]**: Disables DRS on this VM type. VM created with this vm_type will NOT be v-motioned by DRS. 

However now i have run into another issue where i am not able to present the Vsphere Datastores as Persistent volumes via storage class to the K8S cluster , i read a specific github link related to the same issue below  
https://github.com/kubernetes/kubernetes/issues/79809

Any ideas how i can fix this by the turns out that importing the root cert into the host was just a workaround, and the actual bug was fixed in vmware/govmomi#1498. That fix is included in govmomi v0.21.0.

Since i am new to bosh deployment , can you guide me how we can use the above , where and how do i replace the file that has the bug and will there be any impact by simply doing that . 


ESX 6.5 update 3 
Kubenetes version - 1.17 
Bosh Version            271.2.0 (00000000)
Director Stemcell  ubuntu-xenial/621.99
CPI                vsphere_cpi

**Comment by moleske** [comment]
Not sure about persistent volumes, but this sounds like you are using [CFCR](https://docs.cloudfoundry.org/cfcr/).  You might want to check their issues or slack.  This does not seem to be a CPI issue

**Comment by julian-hj** [comment]
Closing this, as it appears that the remaining unresolved issue is a k8s/CFCR issue, and it has been inactive for over a month. Please feel free to re-open if you have further CPI issues.
