### ISSUE TITLE
set_vm_metadata error in greenfield OpsMgr 2.10.14 with use_nsx_policy enabled

### ISSUE THREAD

**Issue by ydp** [cloudfoundry/bosh-vsphere-cpi-release#297]
**Describe the bug**
on a greenfield OpsMgr 2.10.14 deploy in lab
* with use_nsx_policy enabled
```
Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Setting VM metadata to map[created_at:2021-06-24T01:44:10Z deployment:p-bosh director:bosh-init index:0 instance_group:bosh job:bosh name:bosh/0]:
        CPI 'set_vm_metadata' method responded with error: CmdError{"type":"Unknown","message":"The requested object : /infra/segments/haas-237-PAS-Infrastructure/ports/default:e4674c40-48af-4415-a582-6979e6bb0225 could not be found. Object identifiers are case sensitive.","ok_to_retry":false}
```

**To Reproduce**
1. Install OpsMgr 2.10.14 with use_nsx_policy enabled

**CPI Error Log**

**Expected behavior**
OpsMgr install successfully.

**Release Version & Related Info (please complete the following information):**
 - CPI Version  v60

**Additional context**

An initial investigation from @cunnie 

>I don’t know which version of Ops Mgr the bug was introduced, but we believe it appeared in v59 of the BOSH vSphere CPI release on June 3, so any version older than that should not have the bug, and an Ops Manager released after that date should have the bug.
>The bug is a small thing—we use the NSX-T object’s display_name instead of the id in two places, so it should be a quick fix.

**Comment by markstokan** [comment]
Work to address this issue is underway in Tracker Story: https://www.pivotaltracker.com/story/show/178649776

**Comment by markstokan** [comment]
This fix is being released as [Bosh vSphere CPI v61](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/releases/tag/v61)
