### ISSUE TITLE
CPI removing all VMs from pools that share an IP with a bosh managed VM

### ISSUE THREAD

**Issue by miclip** [cloudfoundry/bosh-vsphere-cpi-release#304]
**Describe the bug**
Any VM that shares the same private IP as a bosh managed VM and is also a member of a server pool will removed from the pool by the CPI. The CPI is iterating over all pools and not limited to just pools provided in the configuration when recreating or deleting an instance. 

```ruby
 def remove_vm_from_server_pools(vm_ip)
        services_svc.list_load_balancer_pools.results.each do |server_pool|
        members_found = server_pool.members&.select {|member| member.ip_address == vm_ip}
        next unless members_found&.any?
        members_found.each do |member_found|
          logger.info("Removing vm with ip: '#{vm_ip}', port_no: #{member_found.port} from ServerPool: #{server_pool.id} ")
          pool_member = NSXT::PoolMemberSetting.new(ip_address: vm_ip, port: member_found.port)
          pool_member_setting_list = NSXT::PoolMemberSettingList.new(members: [pool_member])
          services_svc.perform_pool_member_action(server_pool.id, pool_member_setting_list, 'REMOVE_MEMBERS')
        end
      end
    end
```

**To Reproduce**
1. T1s using the same subnets behind different T0 routers
2. A pool configured within each T0 and VMs added to the pools with the same private IP, one is BOSH managed.
3. BOSH will remove both VMs from its pool when only the BOSH managed VM should be removed. 

**CPI Error Log**
No errors but non-deterministic behavior affecting other systems shaing the nsx-t deployment. 

**Expected behavior**
The CPI should limit its operations with pools to only pools listed in the configuration. 

**Release Version & Related Info (please complete the following information):**
 - CPI Version `69*`
 - BOSH Director Version `271.9.0`
 - Stemcell Name & Version `N/A`
 - vCenter Version `7`
 - NSX(T/V) Version (If using) `3`

**Additional context**

**Comment by julian-hj** [comment]
closing and reopening to create a story

**Comment by rkoster** [comment]
@miclip thanks for reporting this issue, the story has been put in our backlog under low priority, which means it could take a while until we get to it. A faster way to get this fix would be to create a Pull Request to fix it (PR reviews have a higher priority).

**Comment by miclip** [comment]
Note that this issue could also impact TKGs or any other product on vsphere using NSX-T load balancing, it's not isolated just to 2 tas deployments sharing the nsx infra.

**Comment by scottgai** [comment]
Yes, one customer just encountered this issue. There are 2 TAS deployments sharing same NSX-T env. One TAS (e.g. TAS1) configured several static IPs for router instances and put them as backend of one server pool. And one temp instance was deployed by BOSH in the other TAS env (e.g. TAS2) to run some errand and the temp instance was assigned same IP (for example, 10.10.10.1) as one of router static IPs in TAS1. When the temp instance was deleted, router backend with IP 10.10.10.1 was also mistakenly removed from server pool. 
`I, [2021-12-16T12:30:24.969942 #4423] INFO -- [req_id cpi-703441]: Removing vm with ip: '10.10.10.1', port_no: 443 from ServerPool: xxxx`

**Comment by rkoster** [comment]
This issue is still being worked on. It is just difficult to keep track of this information. The current direction being explored is using the server pool member `display_name` property to store the parent pool names.

**Comment by miclip** [comment]
thanks for the update @rkoster
