### ISSUE TITLE
persistent_datastore_pattern still required when using persistent_datastore_cluster_pattern

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/bosh-vsphere-cpi-release#306]
**Describe the bug**
When attempting to set both `datastore_cluster_pattern` and `persistent_datastore_cluster_pattern` (and leaving `datastore_pattern` and `persistent_datastore_pattern` undefined per the docs), I'm getting an error when attaching the persistent disk in `bosh create-env`.  This appears to be because the `find_disk` function is still hard-coded to use the `persistent_datastore_pattern` property:

https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/v70/src/vsphere_cpi/lib/cloud/vsphere/resources/datacenter.rb#L127-L128

Defining the `persistent_datastore_pattern` to `.*` or any other valid pattern allows the deploy to complete.

**To Reproduce**
1. Convert an existing BOSH environment using the older patterns to clusters with `bosh create-env`

**CPI Error Log**
`{"result":null,"error":{"type":"Unknown","message":"no implicit conversion of nil into String","ok_to_retry":false},
"log":"Rescued Unknown: no implicit conversion of nil into String. backtrace: /root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/vsphere_cpi/lib/cloud/vsphere/resources/datacenter.rb:128:in 'initialize'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/vsphere_cpi/lib/cloud/vsphere/resources/datacenter.rb:128:in 'new'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/vsphere_cpi/lib/cloud/vsphere/resources/datacenter.rb:128:in 'find_disk'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/vsphere_cpi/lib/cloud/vsphere/cloud.rb:610:in 'block in attach_disk'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/vsphere_cpi/vendor/bundle/ruby/2.6.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in 'with_thread_name'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/vsphere_cpi/lib/cloud/vsphere/cloud.rb:607:in 'attach_disk'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/lib/ruby/2.6.0/forwardable.rb:230:in 'attach_disk'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/vsphere_cpi/vendor/bundle/ruby/2.6.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in 'public_send'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/vsphere_cpi/vendor/bundle/ruby/2.6.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in 'run'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/vsphere_cpi/bin/vsphere_cpi:72:in '<top (required)>'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in 'load'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in 'kernel_load'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:28:in 'run'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:476:in 'exec'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in 'run'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'invoke_command'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:399:in 'dispatch'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:30:in 'dispatch'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:476:in 'start'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:24:in 'start'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/exe/bundle:46:in 'block in <top (required)>'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:123:in 'with_friendly_errors'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/exe/bundle:34:in '<top (required)>'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/bin/bundle:23:in 'load'
/root/.bosh/installations/627c7175-a059-4b44-4c6e-2215b3489ebf/packages/ruby-2.6.5-r0.29.0/bin/bundle:23:in '<main>'"}`

**Expected behavior**
`bosh create-env` should run without error and attached persistent disk.

**Release Version & Related Info (please complete the following information):**
 - CPI Version:  70
 - BOSH Director Version:  271.11.0
 - Stemcell Name & Version:  bosh-stemcell-1.33-vsphere-esxi-ubuntu-bionic-go_agent.tgz
 - vCenter Version:  6.7
 - NSX(T/V) Version (If using):  N/A

**Comment by julian-hj** [comment]
Thanks @amhuber this definitely looks like a bug that should be addressed. While you are waiting for us to correct it, I think as a workaround you can just put an unmatchable regex into the `persistent_datastore_pattern` (e.g. "^$") and it should start working for you. Provided that the value isn't nil, the code should carry on and find your datastore in one of the accessible clusters.

**Comment by amhuber** [comment]
Yep, I mentioned in the issue that it works with any valid pattern.  I'm using `.*` right now, and using `^$` would be equivalent (searching all datastores), it would just do it in the "other" code block.

**Comment by amhuber** [comment]
Yeah, agreed this isn't urgent.  To be honest, if you just update the docs to indicate you need to use ".*" for the persistent_datastore_pattern when using the cluster options you could just leave it at that.

**Comment by amhuber** [comment]
I looked at all the places where those values were used and the cluster settings would take precedence if they were configured, other than the code mentioned in this issue that was specifically for finding a detached persistent disk.  In that code, if the configured regex doesn't match (for example by using `^$`), then it will fall back to searching all datastores anyway.  Given that, I couldn't find anything that would work differently with `.*` or `^$`.

If you are aware of a location where the non-cluster regex will override the cluster regex, then I'd appreciate it if you could point out the code.

**Comment by amhuber** [comment]
Ah, thanks, I missed that `OR` in the logic, that will definitely cause an issue.  I'll use `^$` until this is fixed.

**Comment by julian-hj** [comment]
closing and reopening to make a new tracker story
