### ISSUE TITLE
Agent unresponsive after bosh redeploy

### ISSUE THREAD

**Issue by matteowiz** [cloudfoundry/bosh-vsphere-cpi-release#308]
Hello,

using ops manager2.10.19, TAS for VMs 2.11 and TAS for VMs (windows) 2.10 over vsphere clusters. (vcenter6.7, esx6.5, NSX-v 6.4.6) I noticed that after every BOSH director redeploy, it always find all the VMs agents unresponsive except the windows diego cells. Is it a normal behaviour? it then takes hours to recreate all the vms.

Another question I have, I noticed the create_vm task is taking about 10 minutes, from the cpi logs I see that 7-8 minutes are spent in "Applying Security Groups" tasks. 

As we have the same setup on AWS, the create_vm task takes only around 1 minute and 30seconds.

Is it a limitation coming fron NSX-v? where can I find a list of supported NSX-v version? (we are at 6.4.6 but vmware latest is 6.4.11)

Thanks in advance,

Best regards,

--
matteo
---

You can also reach out to us via:

* Slack: http://cloudfoundry.slack.com/messages/bosh-cpi-dev

**Comment by bgandon** [comment]
Hi @matteowiz,

This is definitely not a normal behaviour. What you need to understand, is why the Agents suddenly don't manage to properly communicate with the Director. A networking issue is definitely a relevant assumption that you can make and then need to validate.

Here, you are posting on an Open Source project for a Bosh CPI which has nothing to do with the inability of your Bosh Agents to communicate with the Director, plus, you're using a VMware Tanzu product and should have related enterprise support with it, that you should reach out to in the first place.

So, please tripple-check your security groups and network design, and also raise a ticket to the VMware support and they should help you track the problem down. In case you run out of options, you can contact some other independant Bosh Service Provider that can provide the necessary expertise to help you fix this issue. You can reach out by private message for any further assistance.
