### ISSUE TITLE
BOSH Vsphere CPI APIs to automatically add diego cell or BOSH VM on which garden containers can be deployed on .

### ISSUE THREAD

**Issue by viju2008** [cloudfoundry/bosh-vsphere-cpi-release#313]
### Detailed Description

BOSH API/Commands to add diego cell or Create VM (using Vsphere CPI) on which containers can be deployed on.

Currently a new diego cell has to be provisioned manually on Vsphere environment

### Context
. We wish to automate it using scripts so that based on load a new diego cell can be provisioned automatically on the Vsphere environment on the same physical host or another physical host.

This will help users to not only scale containers but also the underlying VMs on which containers are deployed on

### Possible Implementation
Bosh vsphere CPI could provide apis to provision new  diego Cells 

### Complexity

Medium

**Comment by beyhan** [comment]
We discussed this topic in cloudfoundry/bosh-deployment#426.
