### ISSUE TITLE
bump to ruby 3.1.x for upcoming jammy release

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh-vsphere-cpi-release#318]
the new jammy based stemcells are using openssl 3 by default.
ruby >= 3.1.0 has openssl 3 support,

i also noticed that the https://github.com/vmware/vsphere-automation-sdk-ruby
we rely on is now deprecated.

**Comment by metron2** [comment]
This is still maintained https://github.com/vmware/govmomi

**Comment by rkoster** [comment]
There is a PR here: https://github.com/cloudfoundry/bosh-vsphere-cpi-release/pull/320
