### ISSUE TITLE
Airgap compile (still) not working in v78 (release notes claim fixed in this release)

### ISSUE THREAD

**Issue by ae-govau** [cloudfoundry/bosh-vsphere-cpi-release#335]
**Describe the bug**

After updating `bosh-deployment` to one that references v78, we see the following error:

```
Task 7637065 | 06:04:37 | Compiling packages: vsphere_cpi/153ae717fd4159e49c5cba50582814524f63c6f9aeabf80a34ebd02191f91eed (00:00:15)
                        L Error: Action Failed get_task: Task 054b82e9-52b3-463e-546c-58c096690e72 result: Compiling package vsphere_cpi: Running packaging script: Running packaging script: Command exited with 17; Stdout: , Stderr: + BOSH_PACKAGES_DIR=/var/vcap/packages
+ source /var/vcap/packages/ruby-3.1.2-r0.91.0/bosh/compile.env
++ source /var/vcap/packages/ruby-3.1.2-r0.91.0/bosh/runtime.env
+++ export PATH=/var/vcap/packages/ruby-3.1.2-r0.91.0/bin:/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin
+++ PATH=/var/vcap/packages/ruby-3.1.2-r0.91.0/bin:/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin
+++ export GEMRC=/var/vcap/packages/ruby-3.1.2-r0.91.0/bosh/gemrc
+++ GEMRC=/var/vcap/packages/ruby-3.1.2-r0.91.0/bosh/gemrc
+ cp -a vsphere_cpi/Gemfile vsphere_cpi/Gemfile.lock vsphere_cpi/bin vsphere_cpi/lib vsphere_cpi/vendor /var/vcap/packages/vsphere_cpi
+ cd /var/vcap/packages/vsphere_cpi
+ bundle config set --local deployment true
+ bundle config set --local no_prune true
+ bundle config set --local without 'development test'
+ bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Could not reach host index.rubygems.org. Check your network connection and try
again.
```

Our environment does not have direct internet access.

**To Reproduce**

Attempt to install BOSH director in environment that does not have internet access.

**CPI Error Log**

Didn't get that far.

**Expected behavior**

It to compile successfully (like v76 does)

**Screenshots**

**Release Version & Related Info (please complete the following information):**

 - CPI Version  - `v78 `
 - BOSH Director Version - `273.1.0`
 - Stemcell Name & Version - `ubuntu-bionic 1.97`
 - vCenter Version - n/a
 - NSX(T/V) Version (If using) - n/a

**Comment by ae-govau** [comment]
Not sure if helpful or not, but the `capi-release` folks have had similar issues... https://github.com/cloudfoundry/capi-release/pull/261

One thing I've found helpful during testing to weed out internet connections is to set env vars `HTTPS_PROXY=http://localhost:4322` and `HTTP_PROXY=http://localhost:4322` where nothing is running on 4322. This tends to fail fast, and you can add `NO_PROXY=bosh.io` for anything you really do need to access for the test.

**Comment by rkoster** [comment]
v79 includes further changes needed to fix air-gapped environments: https://github.com/cloudfoundry/bosh-vsphere-cpi-release/releases/tag/v79
