### ISSUE TITLE
Required privileges on datacenter level for multi-tenancy within a VCenter

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/bosh-vsphere-cpi-release#34]
Hi guys

We try to set up multiple CloudFoundries in a single VCenter. To achieve the best isolation possible, we would like to have a separate VCenter user for each CloudFoundry, and each user should be granted only the least privileges possible. The goal would be that user for CloudFoundry A can not access stuff from CloudFoundry B.

To separate the different CloudFoundries, we created a *folder* in VCenter for each CloudFoundry. On this Folder we applied the necessary permissions as [listed in the docs](docs/required_vcenter_privileges.md).

However, some of the permissions can not be set on a Folder level but must be set on Datacenter level. We had to grant the users these privileges on Datacenter level to get basic deployments working:

```
Datastore.AllocateSpace
Datastore.Browse
Datastore.FileManagement
Datastore.DeleteFile
Datastore.UpdateVirtualMachineFiles
Network.Assign
Resource.AssignVMToPool 
VirtualMachine.Config.AddNewDisk
VApp.Import
```

However, if we grant one user these privileges on a global level, it can access other user's data in the datastores or access other user's networks, breaking the separation. 

Is there a way to still achieve the desired isolation?

We're aware that for some of these privileges, we could work around by separating resources (i.e. create separate data stores for each cloudfoundry), but then we lose some of the 'Cloudy' properties.

**Comment by cppforlife** [comment]
@MatthiasWinzeler i suspect that vsphere doesnt have more fine grained controls around these resources. will try to reach to someone from vmware to find out more.

**Comment by ktchen14** [comment]
Previous link is broken. This is the correct link to the [documentation](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/master/docs/required_vcenter_privileges.md).

**Comment by EleanorRigby** [comment]
The document shared above provides a complete set of permissions. It also does away with most of the permissions at the Datacenter and global level. 

Feel free to open the issue if the document is unsatisfactory.
