### ISSUE TITLE
Unable to upload Jammy stemcell - "Permission to perform this operation was denied"

### ISSUE THREAD

**Issue by brunograz** [cloudfoundry/bosh-vsphere-cpi-release#352]
We are trying to upload Jammy stemcells on vsphere but running into `Permission Denied` issues, bionic still work as usual. See error below:
`W, [2022-11-04T09:10:13.781223 #3631]  WARN -- [req_id cpi-246645]: Error running method 'ImportVApp'. Failed with message 'Permission to perform this operation was denied.'.`

We've checked the stemcell and noticed a difference between the OVF files. More precisely,  Jammy stemcells have an additional section as below:
`<vmw:ExtraConfig ovf:required="false" vmw:key="nvram" vmw:value="nvram"/>
<vmw:ExtraConfig ovf:required="false" vmw:key="virtualHW.productCompatibility" vmw:value="hosted"/>
`
Does the user require additional permissions to upload the stemcells that are not listed at https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/master/docs/required_vcenter_privileges.md? 

**To Reproduce**
1. Upload any Jammy stemcell - considering strictly the permissions above.

**Expected behavior**
1. Stemcell uploaded to vSphere

**Release Version & Related Info (please complete the following information):**
 - BOSH Director: 273.1.0
 - vCenter Version: Tested on 6.7 and 7.0

**Comment by brunograz** [comment]
After further investigation we've come to find that it was actually a lack of permission on our side. More specifically `Configuration > Advanced | VirtualMachine.Config.AdvancedConfig` was missing at datastore level but it was implemented at folder level.

Closing this ticket as the documentation does not lack any additional permission.

**Comment by cunnie** [comment]
Nice troubleshooting, Bruno! I'm glad it's fixed.
