### ISSUE TITLE
Support for vSphere 8

### ISSUE THREAD

**Issue by JoschuaA4** [cloudfoundry/bosh-vsphere-cpi-release#355]
### Detailed Description
bosh-vsphere-cpi currently supports vSphere 6.5/6.7/7.0 but vSphere 8 ist GA for nearly 6 Month now. Support for vSphere 8 would be needed.

### Context
We are using Tnazu Kuberntes Grid Integrated Edition which only supports vSphere 7. One reason seems to be that bosh-vsphere-cpi does not support vSphere 8 yet.
In the near future other customers need to upgrade there vSphere environments to Version 8.

### Possible Implementation
Sorry, but i don't now anything about the code base of bosh-vsphere-cpi.

### Complexity
- [x ] Medium - Change requires some thought, but is relatively isolated
As i mention above, i don't now anything about your code base but i would think that most of the functionality of vSphere 7 will be the same for Version 8.

**Comment by cunnie** [comment]
@JoschuaA4 :

> bosh-vsphere-cpi currently supports vSphere 6.5/6.7/7.0 but vSphere 8 ist GA for nearly 6 Month now. Support for vSphere 8 would be needed.

Absolutely! We want to certify the BOSH vSphere CPI with vSphere 8. In fact, we're actively working on it. The big challenge we're currently overcoming is setting up the testbeds to certify vSphere 8. To go a step further, the portion that's proving the most challenging is making sure we test against NSX 4.0.1 (the only version of NSX that supports vSphere 8).

From an informal standpoint, the BOSH vSphere CPI works fine out-of-the-box with vCenter 8—my personal foundation has been running on vCenter 8 for the last few months (unfortunately no NSX). But that's not enough to certify vSphere 8 compatibility. We want to make sure every change we make to the CPI code is subjected to a battery of tests against vSphere 8 + NSX 4.0.1 environments, and we're working on that right now.

**Comment by jpalermo** [comment]
[v90](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/releases/tag/v90) is now tested against vSphere 8. I don't believe there were any actual changes in the CPI to work with vSphere 8, so older versions are also likely to work, but now we test against it.
