### ISSUE TITLE
The CPI doesn't delete nsx security group, created for a particular vm, after the vm is deleted.

### ISSUE THREAD

**Issue by s-matyukevich** [cloudfoundry/bosh-vsphere-cpi-release#79]
Because of this behavior right now we are having 3000+ security groups. Sometimes this causes new deployments to fail, because [this](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/master/src/vsphere_cpi/lib/cloud/vsphere/nsx.rb#L273) method times out.

**Comment by cppforlife** [comment]
i wonder if we should have some kind of pruning script in the background. problem is though cpi needs to use cpi configs to connect to vsphere.

**Comment by s-matyukevich** [comment]
Can somebody explain why we can't simply delete the security group, associated with a VM, at the time when the VM is deleted? I saw [this](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/1d5a5c4d97abbed9fdb98a8cf6d4a6b725078198/src/vsphere_cpi/lib/cloud/vsphere/nsx.rb#L53) comment in the CPI source code, but I still don't understand how we can affect other security groups when deleting a specific one?

**Comment by cppforlife** [comment]
multiple vms share a sec group, and there might be a race between deleting all vms in a sec grpup and deleteing it as well, and creating new vms in that instance group (which would require sec group presence). things are made more complicated by nsxt not making it easier to have objects unique based on a given identifier.

**Comment by aeijdenberg** [comment]
Perhaps the auto-creation of security groups to match the set of BOSH groups can be made configurable, and disabled by default (or at least optional to disable)? If no policies refer to them, then it's not clear why they need to be created at all.
