### ISSUE TITLE
VMFork with BOSH

### ISSUE THREAD

**Issue by NiranEC77** [cloudfoundry/bosh-vsphere-cpi-release#87]
With vSphere 6.7 VMware enabled the ability to invoke VMFork through the API, this means one can power on hundreds of VMs at once using linked cloning technologies.
This can be of great value for BOSH as anyone working with BOSH knows the pain of waiting for BOSH waiting minutes for each VM to come up. in comparison to the cloud that time is unacceptable. If taking advantage of VMFork BOSH can deploy many VMs at once and power them on at the same time shrinking time for deployment and ops immensely.
I believe this would be of great value to our customer and have a real impact for our customers

Thanks,
Niran

**Comment by julian-hj** [comment]
We did a series of investigations of instant cloning VMs during bosh deployment
https://www.pivotaltracker.com/story/show/177255926
https://www.pivotaltracker.com/story/show/177255861
https://www.pivotaltracker.com/n/projects/2475776/stories/177045187

The upshot for TAS customers is that most of the time spent in redeployment is taken by the `drain` step, so overall we don't think cloning VMs would have enough of a benefit to justify the risk accompanying the big logical flow changes we would incur.
